// Register: 50 urban districts. `r` is the district radius (km); `bldg` is
// [min height m, max height m, coverage 0–1] used by the 3D explorer.

export const DISTRICTS = [
  // ------------------------------------------------------------ Calder Island
  { id: 'downtown', name: 'Downtown Calder', island: 'calder', at: [37.8, 61.9], r: 0.75, bldg: [40, 270, 0.75], form: 'high-rise core',
    desc: 'The central business district on the bluff at the river mouth: glass and limestone towers up to 64 storeys, the old customs house, and narrow streets laid out on the colonial grid.',
    why: 'The first dry ground above the deep anchorage at the Tennalee mouth; land values here have always been the highest on the island.',
    look: 'A tight cluster of towers on a bluff, the tallest crowned with a lit spire.',
    near: 'Old Market, Station Square, Market Street Bridge, Calder Tower.',
    memorable: 'The skyline rising straight out of the water when seen from the Tennalee River Bridge.' },
  { id: 'old-market', name: 'Old Market', island: 'calder', at: [39.0, 62.6], r: 0.45, bldg: [8, 20, 0.7], form: 'historic waterfront',
    desc: 'Three- and four-storey brick warehouses, cobbled streets and an open-sided market shed along the wharves.',
    why: 'The original deep-water wharves below the bluff.',
    look: 'Red brick, iron balconies and cobblestones.',
    near: 'Calder Wharves, Downtown, Ferry Landing.',
    memorable: 'Cobbles glistening after summer storms.' },
  { id: 'calder-point', name: 'Calder Point', island: 'calder', at: [40.9, 61.2], r: 0.45, bldg: [8, 16, 0.55], form: 'historic residential',
    desc: 'The oldest houses on the island, tall and narrow, behind a high seawall promenade and a park at the tip.',
    why: 'The point at the junction of the North Channel and the Inner Harbor, the first place settled.',
    look: 'Pastel facades along a curving seawall.',
    near: 'Calder Harbor Light, Old Market, Harbor Bridge.',
    memorable: 'Watching ships turn into the harbour from the seawall.' },
  { id: 'station-square', name: 'Station Square', island: 'calder', at: [36.8, 61.7], r: 0.35, bldg: [15, 60, 0.7], form: 'transit hub',
    desc: 'The district around Calder Central station, with its clock tower, hotels and the bus terminal.',
    why: 'Where the passenger railroad crosses the Market Street Bridge into the city.',
    look: 'A stone clock tower among mid-rise hotels.',
    near: 'Calder Central, Downtown, Market Street Bridge.',
    memorable: 'The station clock tower lit at night.' },
  { id: 'midtown', name: 'Midtown', island: 'calder', at: [36.4, 60.4], r: 0.6, bldg: [20, 110, 0.65], form: 'mid-rise mixed',
    desc: 'Office and apartment towers of the 1960s–2000s along the main avenue south of Downtown.',
    why: 'The commercial spillover from Downtown along the interstate spur.',
    look: 'Mid-rise blocks and a canyon of an avenue.',
    near: 'I-121, Downtown, The Heights.',
    memorable: 'Afternoon thunderstorms funnelling down the avenue.' },
  { id: 'uptown', name: 'Uptown', island: 'calder', at: [34.6, 61.8], r: 0.55, bldg: [15, 90, 0.6], form: 'residential towers',
    desc: 'Apartment towers along the North Channel shore with balconies facing the mountains.',
    why: 'North-facing waterfront with views of the Halcomb range.',
    look: 'Towers with the North Face behind them.',
    near: 'Tennalee River Bridge, Downtown.',
    memorable: 'Mountains reflected in the channel.' },
  { id: 'northpoint', name: 'Northpoint', island: 'calder', at: [32.4, 61.4], r: 0.55, bldg: [8, 30, 0.55], form: 'residential',
    desc: 'A neighbourhood of walk-up apartments and bungalows at the island\'s north-west corner.',
    why: 'The flat end of the island beside the interstate bridge.',
    look: 'Low streets under the bridge approach.',
    near: 'I-21, Gasworks.',
    memorable: 'Living under the bridge ramps.' },
  { id: 'the-heights', name: 'The Heights', island: 'calder', at: [35.2, 59.2], r: 0.55, bldg: [8, 18, 0.35], form: 'historic residential',
    desc: 'Large Victorian and Colonial Revival houses on the granite ridge, with old oaks over the streets.',
    why: 'The highest, coolest and best-drained ground in the city.',
    look: 'Big houses and big trees on a hill.',
    near: 'Heights Reservoir, Calder Heights tower.',
    memorable: 'Oak canopy over brick-paved streets.' },
  { id: 'reservoir-hill', name: 'Reservoir Hill', island: 'calder', at: [34.4, 58.2], r: 0.45, bldg: [8, 16, 0.45], form: 'residential',
    desc: 'Terraced streets descending the south side of the ridge from the reservoir.',
    why: 'Slopes of the Heights.',
    look: 'Stepped streets and stairs.',
    near: 'Heights Reservoir Park.',
    memorable: 'Public stairways between streets.' },
  { id: 'mill-creek', name: 'Mill Creek', island: 'calder', at: [37.4, 58.6], r: 0.5, bldg: [8, 16, 0.65], form: 'rowhouses',
    desc: 'Rowhouses in the shallow valley of a creek now buried in a brick culvert; its stone outfall still opens onto the harbour.',
    why: 'The only stream valley on the island, built over as the city grew.',
    look: 'Rows of narrow brick houses on a curving street.',
    near: 'Midtown, Stadium District.',
    memorable: 'The street follows the curve of the buried creek.' },
  { id: 'westside', name: 'Westside', island: 'calder', at: [31.4, 59.6], r: 0.55, bldg: [8, 25, 0.5], form: 'residential',
    desc: 'Apartment buildings and townhouses along Westside Park and the bay shore.',
    why: 'Sheltered west shore facing Serena Bay.',
    look: 'Buildings framing the park.',
    near: 'Westside Park, Lake Ellery.',
    memorable: 'Sunsets over the bay from the park.' },
  { id: 'ellery-park', name: 'Ellery Park', island: 'calder', at: [31.9, 58.2], r: 0.45, inWater: true, bldg: [0, 0, 0], form: 'park', cover: 'park',
    desc: 'The city\'s great park around Lake Ellery: lawns, oak woods, cypress lake and a boathouse.',
    why: 'Wet ground at a former tidal creek, never built on.',
    look: 'Green against the grid.',
    near: 'Lake Ellery, Westside, Westside Park Beach.',
    memorable: 'Cypress trees in the middle of a city.' },
  { id: 'yacht-basin', name: 'Yacht Basin', island: 'calder', at: [31.3, 57.4], r: 0.45, bldg: [6, 20, 0.45], form: 'marina',
    desc: 'Marinas, boat storage and waterfront restaurants on the south-west shore.',
    why: 'Sheltered water on the lee side of the island.',
    look: 'Masts and boat sheds.',
    near: 'Calder Yacht Basin, University.',
    memorable: 'Forest of masts at sunset.' },
  { id: 'south-shore', name: 'South Shore', island: 'calder', at: [36.6, 55.8], r: 0.6, bldg: [8, 40, 0.55], form: 'waterfront residential',
    desc: 'Apartments and houses along the seawall facing Saint Ambrose.',
    why: 'South-facing shore across the narrow sound.',
    look: 'Seawall promenade and palms.',
    near: 'South Shore Beach, Long Bridge.',
    memorable: 'The Long Bridge hump at sunset.' },
  { id: 'southside', name: 'Southside', island: 'calder', at: [38.8, 56.2], r: 0.5, bldg: [8, 20, 0.6], form: 'industrial',
    desc: 'Warehouses, the wastewater plant and truck yards on reclaimed land.',
    why: 'Low, filled land at the south-east corner.',
    look: 'Flat roofs and tanks.',
    near: 'Calder Southside Treatment Plant, Stadium District.',
    memorable: 'The digester eggs of the treatment plant.' },
  { id: 'harborside', name: 'Harborside', island: 'calder', at: [40.8, 58.4], r: 0.55, bldg: [10, 50, 0.6], form: 'converted warehouses',
    desc: 'Old cotton and tobacco warehouses on the Inner Harbor converted to lofts and offices.',
    why: 'The east shore facing Corliss, once the main freight wharves.',
    look: 'Long brick warehouses with painted signs.',
    near: 'Harbor Bridge, Arts District.',
    memorable: 'Ghost signs on brick walls.' },
  { id: 'arts-district', name: 'Cotton Exchange', island: 'calder', at: [39.6, 60.4], r: 0.45, bldg: [8, 30, 0.7], form: 'historic commercial',
    desc: 'The old cotton exchange building and surrounding commercial blocks, now galleries and studios.',
    why: 'The trading district behind the wharves.',
    look: 'Ornate commercial facades.',
    near: 'Harborside, Downtown.',
    memorable: 'The exchange building\'s copper dome.' },
  { id: 'hospital-hill', name: 'Hospital Hill', island: 'calder', at: [36.4, 58.4], r: 0.4, bldg: [15, 70, 0.6], form: 'institutional',
    desc: 'Calder General Hospital and medical buildings on the east shoulder of the Heights.',
    why: 'Built on high ground above the flood zone.',
    look: 'White hospital towers with a helipad.',
    near: 'The Heights, Midtown.',
    memorable: 'Helicopters landing on the roof.' },
  { id: 'university', name: 'University', island: 'calder', at: [33.2, 57.0], r: 0.6, bldg: [8, 40, 0.4], form: 'campus',
    desc: 'The campus of Calder State University: brick quadrangles, live oaks and a bell tower.',
    why: 'Quiet south-west part of the island.',
    look: 'Bell tower over oak-shaded lawns.',
    near: 'Yacht Basin, Fairgrounds.',
    memorable: 'The bell tower above the trees.' },
  { id: 'stadium-district', name: 'Stadium District', island: 'calder', at: [39.4, 57.4], r: 0.45, bldg: [10, 50, 0.55], form: 'entertainment',
    desc: 'The football stadium and arena on filled land near the harbour.',
    why: 'Large flat site on reclaimed land with highway access.',
    look: 'The stadium bowl and its lights.',
    near: 'Mill Creek, Southside.',
    memorable: 'Stadium lights glowing over the harbour on game nights.' },
  { id: 'cypress-row', name: 'Cypress Row', island: 'calder', at: [38.4, 60.2], r: 0.35, bldg: [8, 14, 0.7], form: 'historic rowhouses',
    desc: 'Painted rowhouses with deep porches on a street lined with cypress planters.',
    why: 'Old middle-class streets between the wharves and the Heights.',
    look: 'Pastel rowhouses.',
    near: 'Cotton Exchange, Midtown.',
    memorable: 'A row of brightly painted porches.' },
  { id: 'brickyard', name: 'Brickyard', island: 'calder', at: [33.6, 59.8], r: 0.4, bldg: [8, 24, 0.6], form: 'lofts',
    desc: 'A former brickworks with kilns and chimneys now converted to lofts and studios.',
    why: 'The clay pits along the ridge supplied brick for the old city.',
    look: 'Beehive kilns and brick chimneys.',
    near: 'The Heights, Northpoint.',
    memorable: 'Old kilns used as cafes.' },
  { id: 'gasworks', name: 'Gasworks', island: 'calder', at: [32.6, 60.6], r: 0.35, bldg: [8, 30, 0.6], form: 'post-industrial',
    desc: 'A district around the iron frame of an old gasholder, now a park and apartments.',
    why: 'The old town gasworks by the water.',
    look: 'A giant iron ring of the gasholder frame.',
    near: 'Northpoint, Uptown.',
    memorable: 'The gasholder frame lit at night.' },
  { id: 'fairgrounds', name: 'Fairgrounds', island: 'calder', at: [34.4, 56.4], r: 0.45, bldg: [6, 15, 0.35], form: 'mixed',
    desc: 'The county fairgrounds and exposition hall with surrounding bungalows.',
    why: 'Open ground on the south side of the island.',
    look: 'Exhibition halls and a grandstand.',
    near: 'University, South Shore, I-21.',
    memorable: 'The Ferris wheel at fair time.' },
  { id: 'ferry-landing', name: 'Ferry Landing', island: 'calder', at: [39.7, 62.35], r: 0.3, bldg: [8, 25, 0.55], form: 'transport',
    desc: 'The ferry terminal for the Graystone ferry and the heliport pier.',
    why: 'Deep water at the tip of the bluff.',
    look: 'Ferry slips and a helipad pier.',
    near: 'Old Market, Calder Point.',
    memorable: 'The ferry horn echoing off the towers.' },

  // ----------------------------------------------- Halcomb North Shore
  { id: 'mill-district', name: 'Tennalee Falls Mill District', island: 'halcomb', at: [36.9, 65.9], r: 0.5, bldg: [10, 30, 0.6], form: 'historic industrial',
    desc: 'Brick textile mills four and five storeys high along the river below the falls, with a tall chimney and a mill race.',
    why: 'Water power at the fall line.',
    look: 'Red brick mills beside white water.',
    near: 'Tennalee Falls, Main Line station.',
    memorable: 'The falls roaring between the mills.' },
  { id: 'riverside', name: 'Riverside', island: 'halcomb', at: [39.2, 65.6], r: 0.6, bldg: [8, 25, 0.55], form: 'residential and wharves',
    desc: 'Barge wharves and working-class neighbourhoods on the terrace east of the river mouth.',
    why: 'Low terrace at the river mouth facing downtown.',
    look: 'Barges and frame houses.',
    near: 'Riverside Barge Terminal, Tennalee Junction.',
    memorable: 'View of the downtown skyline across the channel.' },
  { id: 'halcomb-heights', name: 'Halcomb Heights', island: 'halcomb', at: [32.8, 66.0], r: 0.8, bldg: [6, 12, 0.35], form: 'suburb',
    desc: 'Commuter suburbs on the foothill ridges above the North Channel.',
    why: 'The first ridges beyond the bridge.',
    look: 'Houses among trees on hills.',
    near: 'I-21, Tennalee River Bridge.',
    memorable: 'Houses with mountain and city views.' },
  { id: 'falls-hill', name: 'Falls Hill', island: 'halcomb', at: [36.0, 67.2], r: 0.45, bldg: [6, 12, 0.4], form: 'historic residential',
    desc: 'Mill owners\' houses on the hill above the falls.',
    why: 'High ground overlooking the mills.',
    look: 'Large houses on a wooded hill.',
    near: 'Mill District, Tennalee Water Works.',
    memorable: 'Porches overlooking the falls.' },
  { id: 'tennalee-junction', name: 'Tennalee Junction', island: 'halcomb', at: [40.4, 65.8], r: 0.4, bldg: [6, 15, 0.5], form: 'rail yard',
    desc: 'The rail junction where the freight line to Corliss leaves the main line.',
    why: 'The last land before the long lift bridge.',
    look: 'Tracks, signals and freight cars.',
    near: 'Corliss Lift Bridge, Riverside.',
    memorable: 'Freight trains lining up for the lift bridge.' },

  // ---------------------------------------------------------------- Corliss
  { id: 'corliss-town', name: 'Corliss Town', island: 'corliss', at: [46.0, 57.6], r: 0.7, bldg: [5, 12, 0.55], form: 'worker housing',
    desc: 'Shotgun houses, bungalows and churches on the higher western end of the island.',
    why: 'Housing within walking distance of the port and mills.',
    look: 'Small houses under smokestacks.',
    near: 'Paper Mill, Refinery Row.',
    memorable: 'The mill whistle at shift change.' },
  { id: 'container-terminal', name: 'Container Terminal', island: 'corliss', at: [51.6, 60.8], r: 0.8, bldg: [5, 75, 0.4], form: 'port',
    desc: 'The container port: stacked boxes, straddle carriers and a row of ship-to-shore gantry cranes.',
    why: 'Deep water on the north shore beside the ship channel.',
    look: 'Giant cranes like mechanical giraffes.',
    near: 'Corliss Container Terminal, I-121.',
    memorable: 'Crane booms raised against the sunset.' },
  { id: 'refinery-row', name: 'Refinery Row', island: 'corliss', at: [45.2, 60.2], r: 0.5, bldg: [10, 60, 0.5], form: 'heavy industry',
    desc: 'Tank farm, distillation columns and flare stacks of the refinery.',
    why: 'Tanker berths and pipelines at the west end of the port.',
    look: 'Tanks and towers lit like a city at night.',
    near: 'Corliss Bulk & Tank Berths.',
    memorable: 'The flare stack burning at night.' },
  { id: 'shipyard', name: 'Shipyard', island: 'corliss', at: [55.4, 59.4], r: 0.5, bldg: [10, 90, 0.5], form: 'shipyard',
    desc: 'Drydocks, slipways and a giant goliath crane at the east tip.',
    why: 'Deep water at the island\'s east end.',
    look: 'A goliath crane straddling a drydock.',
    near: 'Corliss Shipyard, Spoil Island Beach.',
    memorable: 'Ships in drydock with their hulls exposed.' },

  // ---------------------------------------------------------------- Bellamy
  { id: 'bellamy-bluffs', name: 'Bellamy Bluffs', island: 'bellamy', at: [30.6, 50.6], r: 1.2, bldg: [6, 14, 0.35], form: 'suburb',
    desc: 'Subdivisions and strip malls on the sandy bluffs south of the Long Bridge.',
    why: 'Commuter access by I-21 and proximity to the airport.',
    look: 'Cul-de-sacs among pines.',
    near: 'I-21, Calder International.',
    memorable: 'Jets low over the rooftops.' },
  { id: 'airport-commerce', name: 'Airport Commerce Park', island: 'bellamy', at: [31.2, 48.2], r: 0.6, bldg: [8, 20, 0.5], form: 'logistics',
    desc: 'Warehouses and distribution centres along I-21 by the airport.',
    why: 'Interstate, airport and port access.',
    look: 'Huge flat-roofed buildings and truck docks.',
    near: 'Bluffs Logistics Park, Calder International.',
    memorable: 'Lines of trucks at dawn.' },
  { id: 'courthouse-square', name: 'Courthouse Square', island: 'bellamy', at: [18.4, 38.6], r: 0.4, bldg: [6, 25, 0.6], form: 'historic town centre',
    desc: 'The domed county courthouse in a square of brick storefronts, with a water tower painted like a peanut.',
    why: 'The centre of the farm county.',
    look: 'Courthouse dome and peanut water tower.',
    near: 'Bellamy Depot, SR 40, SR 9.',
    memorable: 'The peanut-shaped water tower.' },
  { id: 'depot-district', name: 'Depot District', island: 'bellamy', at: [19.2, 37.8], r: 0.4, bldg: [6, 35, 0.55], form: 'agricultural industry',
    desc: 'Railroad depot, cotton gin, peanut shellers and a grain elevator.',
    why: 'Where the railroad meets the farm roads.',
    look: 'Grain elevator towering over the town.',
    near: 'Bellamy & Southern Railway, Ocosta River.',
    memorable: 'Cotton lint drifting in the air at harvest.' },

  // ---------------------------------------------------------------- Mirabel
  { id: 'the-strip', name: 'The Strip', island: 'mirabel', at: [4.7, 45.8], r: 0.7, bldg: [6, 40, 0.65], form: 'resort commercial',
    desc: 'The beach road lined with motels, souvenir shops, seafood restaurants and mini golf.',
    why: 'The resort grew along the beach road nearest the causeway.',
    look: 'Neon signs and palms.',
    near: 'Mirabel Pier, Pier Beach.',
    memorable: 'Neon at night.' },
  { id: 'pier-district', name: 'Pier District', island: 'mirabel', at: [4.2, 47.0], r: 0.4, bldg: [6, 25, 0.6], form: 'amusement',
    desc: 'Boardwalk amusements, a Ferris wheel and arcades at the foot of the pier.',
    why: 'The pier is the focus of the resort.',
    look: 'Ferris wheel by the sea.',
    near: 'Mirabel Pier, The Strip.',
    memorable: 'The Ferris wheel lit at night.' },
  { id: 'condo-row', name: 'Condo Row', island: 'mirabel', at: [4.4, 42.8], r: 0.8, bldg: [30, 95, 0.5], form: 'high-rise resort',
    desc: 'A wall of 20- to 30-storey condominium towers along the beach.',
    why: 'Beachfront land at its most valuable.',
    look: 'White towers in a line.',
    near: 'Mirabel Beach, Lake Mirabel.',
    memorable: 'Towers glowing pink at sunset.' },
  { id: 'port-serena-harbor', name: 'Port Serena Harbor', island: 'mirabel', at: [5.2, 28.6], r: 0.45, bldg: [6, 15, 0.5], form: 'marina village',
    desc: 'Marina, charter boats and seafood shacks on the lagoon side of the foreland.',
    why: 'Sheltered lagoon water near the south bridge.',
    look: 'Masts and docks.',
    near: 'Serena Causeway, Port Serena Marina.',
    memorable: 'Charter boats unloading at dusk.' },

  // ------------------------------------------------------------- Haversham
  { id: 'bay-street', name: 'Bay Street', island: 'saint-ambrose', at: [55.0, 48.4], r: 0.35, bldg: [6, 15, 0.7], form: 'historic waterfront',
    desc: 'The waterfront street of brick and tabby stores on the bluff, with a promenade over the river.',
    why: 'The bluff-top landing on the deepest tidal river.',
    look: 'Brick stores and live oaks over the river.',
    near: 'Haversham Shrimp Docks, Bay Street Bluff.',
    memorable: 'Moss hanging over the waterfront.' },
  { id: 'the-point', name: 'The Point', island: 'saint-ambrose', at: [54.4, 49.4], r: 0.4, bldg: [6, 12, 0.4], form: 'historic residential',
    desc: 'Raised houses with deep porches and haint-blue ceilings on oak-shaded streets.',
    why: 'High ground on the bluff north of Bay Street.',
    look: 'Tall raised houses under live oaks.',
    near: 'Bay Street, Haversham Oak Avenue.',
    memorable: 'Houses raised high above floodwaters.' },
  { id: 'shrimp-docks', name: 'Shrimp Docks', island: 'saint-ambrose', at: [55.0, 47.6], r: 0.3, bldg: [5, 10, 0.5], form: 'fishing harbor',
    desc: 'Shrimp boats with their outriggers raised, ice houses and net lofts.',
    why: 'Deep water close to the bluff.',
    look: 'Outriggers and nets.',
    near: 'Haversham Shrimp Docks, Bay Street.',
    memorable: 'Boats unloading at dawn.' },
  { id: 'uptown-haversham', name: 'Uptown Haversham', island: 'saint-ambrose', at: [53.8, 47.4], r: 0.45, bldg: [6, 14, 0.5], form: 'town commercial',
    desc: 'Newer commercial streets and churches back from the river, with three white steeples.',
    why: 'The town\'s growth inland from the bluff.',
    look: 'Three steeples over the rooftops.',
    near: 'Bay Street, Coastal Highway.',
    memorable: 'The steeples visible from the marsh.' },

  // ------------------------------------------------- Graystone and Ledford
  { id: 'graystone-harbor', name: 'Graystone Harbor', island: 'graystone', at: [64.0, 67.8], r: 0.5, bldg: [6, 18, 0.6], form: 'harbour town',
    desc: 'Granite-built harbour town with the ferry terminal and stone wharves.',
    why: 'The sheltered south-facing harbour.',
    look: 'Grey granite buildings by the water.',
    near: 'Graystone Ferry, Grayback.',
    memorable: 'Grayback towering over the harbour.' },
  { id: 'fallon-harbor-village', name: 'Fallon Harbor', island: 'graystone', at: [76.7, 87.9], r: 0.4, bldg: [5, 12, 0.5], form: 'fishing village',
    desc: 'Houses stacked up the cove walls around the fishing harbour.',
    why: 'The only break in the cliffs.',
    look: 'Colourful houses climbing the cliffs.',
    near: 'Fallon Harbor, Cape Fallon Light.',
    memorable: 'Houses on steps above the boats.' },
  { id: 'ledford-strip', name: 'Ledford Parkway Strip', island: 'halcomb', at: [26.9, 68.8], r: 0.6, bldg: [6, 40, 0.6], form: 'tourist strip',
    desc: 'Pancake houses, motels, an aerial tramway and an observation tower along the Gap Road at the foot of the mountains.',
    why: 'Gateway where the Gap Road leaves the foothills.',
    look: 'Billboards and a needle-like observation tower.',
    near: 'Gap Road, Ledford Prong.',
    memorable: 'The tramway cars swinging up the mountainside.' },
  { id: 'narrows-landing-centre', name: 'Narrows Landing', island: 'halcomb', at: [12.0, 89.1], r: 0.4, bldg: [5, 12, 0.5], form: 'small town',
    desc: 'A bridgehead town of motels, gas stations and an old ferry landing under the Narrows Bridge.',
    why: 'Where the bridge lands from the mainland.',
    look: 'The bridge steelwork above the town.',
    near: 'Narrows Bridge, Coldwater Bay.',
    memorable: 'The bridge looming over Main Street.' },
];
