// Register: 50 forests. Each has an elliptical zone (at, rx, ry, rot) and a
// land-cover class that the builder applies within it (only over compatible
// existing cover, so the forest never paints over water, towns or farms
// unless `only` allows it).

const NAT = ['mixed-forest', 'oak-hickory', 'cove-hardwood', 'northern-hardwood', 'spruce-fir', 'flatwoods', 'pine-plantation', 'longleaf', 'maritime-forest', 'bottomland', 'cypress-swamp', 'bay-forest', 'scrub', 'heath-bald', 'pasture', 'cropland', 'orchard', 'fresh-marsh'];

export const FORESTS = [
  // ---------------------------------------------------------------- Halcomb
  { id: 'ledford-spruce-fir', name: 'Ledford Spruce–Fir Forest', island: 'halcomb', at: [29.6, 80.4], rx: 3.6, ry: 1.0, rot: 8, cover: 'spruce-fir', only: ['northern-hardwood', 'spruce-fir'],
    desc: 'The archipelago\'s only boreal forest: dense red spruce and Fraser fir above about 1,850 m, floored with moss, wood sorrel and blowdowns, with grey dead fir on the exposed shoulders.',
    why: 'The summits are cold enough — mean annual temperature near 7 °C — to support a relict northern forest left from colder climates.',
    look: 'Almost black conifer canopy, often in cloud; the trees drip even on dry days.',
    near: 'Ledford Dome, Mount Sawyer, Coldspring Knob, the Parkway.',
    memorable: 'Walking out of a southern hardwood forest into what smells like Canada.' },
  { id: 'balsam-crest-hardwoods', name: 'Balsam Crest Northern Hardwoods', island: 'halcomb', at: [24.0, 78.6], rx: 6.0, ry: 1.2, rot: 25, cover: 'northern-hardwood', only: ['cove-hardwood', 'oak-hickory', 'northern-hardwood'],
    desc: 'A belt of yellow birch, American beech and yellow buckeye along the high crest, twisted by ice storms, with beech gaps of short, gnarled trees in the saddles.',
    why: 'The cool band between the oak forests and the spruce–fir.',
    look: 'Gold in mid-October, earlier than the valleys.',
    near: 'Painted Bald, Stormhead Mountain, the Parkway.',
    memorable: 'Moss-draped birch trunks in fog.' },
  { id: 'callahan-old-growth', name: 'Callahan Old-Growth Coves', island: 'halcomb', at: [32.0, 85.6], rx: 2.2, ry: 1.6, rot: 0, cover: 'cove-hardwood', only: NAT,
    desc: 'Uncut cove forest on the North Face: tulip poplars and buckeyes two metres across, a jungle of rhododendron along the streams, and a ground layer of trillium and fern.',
    why: 'The North Face was too steep for the logging railroads; deep, moist coves facing north grow the largest trees.',
    look: 'Enormous straight grey trunks rising into a closed canopy.',
    near: 'Mount Callahan, Callahan Branch, Big Laurel Creek.',
    memorable: 'Trees so wide three people cannot reach around them.' },
  { id: 'big-laurel-hollows', name: 'Big Laurel Second Growth', island: 'halcomb', at: [37.4, 84.6], rx: 1.6, ry: 2.4, rot: 0, cover: 'cove-hardwood', only: NAT,
    desc: 'Even-aged second-growth forest over the old logging grade, with rusting cable, rail spikes and a collapsed trestle in the hollows.',
    why: 'Logged by railroad a century ago, now grown back as dense young forest.',
    look: 'Straight, crowded trees all the same size.',
    near: 'Big Laurel Logging Grade, Big Laurel Top, Big Laurel Millpond.',
    memorable: 'Iron artefacts of the logging era scattered in the leaf litter.' },
  { id: 'hemlock-ghost-forest', name: 'Hemlock Ghost Forest', island: 'halcomb', at: [36.0, 81.8], rx: 1.0, ry: 0.7, rot: 0, cover: 'cove-hardwood', only: NAT,
    desc: 'A stand of dead eastern hemlocks, grey and needle-less, standing over a thicket of rhododendron and young hardwoods.',
    why: 'Cool, north-facing coves where hemlock once dominated.',
    look: 'A grey patch on the green mountainside.',
    near: 'Hemlock Knob, Big Laurel Creek headwaters.',
    memorable: 'Silent grey trunks above green undergrowth.' },
  { id: 'pigeonroost-laurel-hells', name: 'Pigeonroost Laurel Hells', island: 'halcomb', at: [26.8, 84.4], rx: 0.9, ry: 2.4, rot: 0, cover: 'cove-hardwood', only: NAT,
    desc: 'Impenetrable thickets of rhododendron and mountain laurel along the steep Pigeonroost valley.',
    why: 'Steep, moist, acidic slopes where heaths outcompete trees.',
    look: 'Dense evergreen shrub cover, pink in June.',
    near: 'Pigeonroost Creek, the Gap Road, Blackstrap Knob.',
    memorable: 'The Gap Road switchbacks tunnel through blooming laurel.' },
  { id: 'brushy-oak-pine', name: 'Brushy Mountain Oak–Pine', island: 'halcomb', at: [25.0, 73.6], rx: 1.8, ry: 1.4, rot: 0, cover: 'oak-hickory', only: NAT,
    desc: 'Dry chestnut oak, scarlet oak and pitch pine forest with the grey snags of an old fire.',
    why: 'South-facing slopes and thin soils that dry out every summer.',
    look: 'Open, sunny woods with blueberry underneath.',
    near: 'Brushy Mountain, Chestnut Knob, Lake Hominy.',
    memorable: 'The smell of hot pine needles.' },
  { id: 'tableland-oak-woods', name: 'Hickory Tableland Woods', island: 'halcomb', at: [5.6, 83.0], rx: 2.0, ry: 3.8, rot: 0, cover: 'oak-hickory', only: NAT,
    desc: 'Chestnut oak, hickory and Virginia pine on the flat plateau, with sandstone outcrops and blueberry thickets.',
    why: 'Thin, sandy plateau soils over sandstone.',
    look: 'Flat, open forest on a level horizon.',
    near: 'Hickory Knob, Hickory Lake, Cane Creek.',
    memorable: 'Perfectly flat forest ending at a 400 m cliff.' },
  { id: 'hickory-gorge-hemlocks', name: 'Hickory Gorge Ravines', island: 'halcomb', at: [8.6, 80.8], rx: 0.6, ry: 1.8, rot: 0, cover: 'cove-hardwood', only: NAT,
    desc: 'Shaded ravines below the plateau rim, with waterfalls, hemlock and moss-covered sandstone boulders.',
    why: 'Plateau streams have cut deep, cool gorges into the escarpment.',
    look: 'Green twilight and the sound of falling water.',
    near: 'Hickory Falls, Cane Creek, Coldwater Valley.',
    memorable: 'Cool air pouring out of the gorges on hot days.' },
  { id: 'dogwood-chestnut-oak', name: 'Dogwood Mountain Forest', island: 'halcomb', at: [42.6, 73.4], rx: 1.6, ry: 2.2, rot: 0, cover: 'oak-hickory', only: NAT,
    desc: 'Chestnut oak and hickory with a dense understory of flowering dogwood.',
    why: 'Dry east-facing slopes above Hollow Reach.',
    look: 'White dogwood bloom in April.',
    near: 'Dogwood Mountain, the Gate Road, Upper Cove.',
    memorable: 'Spring bloom visible from the Gate Bridge.' },
  { id: 'cove-mountain-poplars', name: 'Cove Mountain Poplars', island: 'halcomb', at: [30.4, 74.0], rx: 1.4, ry: 1.6, rot: 0, cover: 'cove-hardwood', only: NAT,
    desc: 'Big tulip poplar and basswood in the deep coves on the lake side of Cove Mountain.',
    why: 'Moist, sheltered coves facing the lake.',
    look: 'Tall straight trunks and yellow autumn colour.',
    near: 'Cove Mountain, Calloway Lake, Little River.',
    memorable: 'The yellow coves reflected in the lake in October.' },
  { id: 'coldwater-woodlots', name: 'Coldwater Valley Woodlots', island: 'halcomb', at: [12.0, 77.0], rx: 1.4, ry: 5.0, rot: 0, cover: 'mixed-forest', only: ['pasture', 'cropland'],
    desc: 'Scattered woodlots of oak and red cedar on limestone knobs between the valley pastures.',
    why: 'The rocky knobs are too thin-soiled to plough.',
    look: 'Dark cedar clumps dotting green pasture.',
    near: 'Coldwater, Blue Hole, Old Valley Road.',
    memorable: 'Cedar knobs like islands in the valley floor.' },
  { id: 'hogback-quartzite-woods', name: 'Hogback Woods', island: 'halcomb', at: [38.0, 68.8], rx: 1.2, ry: 0.8, rot: 30, cover: 'oak-hickory', only: NAT,
    desc: 'Pine and oak forest on the narrow quartzite ridge beside the gorge.',
    why: 'Hard, nutrient-poor quartzite.',
    look: 'Thin forest over white rock ledges.',
    near: 'The Hogback, Calloway Dam, Tennalee Falls.',
    memorable: 'White quartzite glinting through the trees.' },

  // -------------------------------------------------------------- Graystone
  { id: 'blue-wall-rainforest', name: 'Blue Wall Rainforest', island: 'graystone', at: [64.0, 79.0], rx: 9.0, ry: 1.3, rot: 26, cover: 'cove-hardwood', only: NAT,
    desc: 'A temperate rainforest on the escarpment face: hemlock, rhododendron, ferns, mosses and liverworts on every surface, with waterfalls in every ravine.',
    why: 'Moist sea air rises up the escarpment and drops over 2,500 mm of rain a year — the wettest place in the islands.',
    look: 'Saturated green; the escarpment seems to steam after rain.',
    near: 'Glassface Dome, Thunderhole Gorge, the Whitlock Grade.',
    memorable: 'Moss so thick the rocks look upholstered.' },
  { id: 'thunderhole-gorge-forest', name: 'Thunderhole Gorge Forest', island: 'graystone', at: [60.6, 77.6], rx: 0.9, ry: 2.0, rot: 20, cover: 'cove-hardwood', only: NAT,
    desc: 'Old forest on the walls of the gorge, too steep ever to have been cut.',
    why: 'Inaccessible gorge walls.',
    look: 'Dense forest clinging to steep walls.',
    near: 'Thunderhole Falls, Thunderhole River.',
    memorable: 'The roar of the falls through the trees.' },
  { id: 'whitlock-highland-forest', name: 'Whitlock Highland Forest', island: 'graystone', at: [60.0, 85.2], rx: 5.0, ry: 1.6, rot: 10, cover: 'northern-hardwood', only: NAT,
    desc: 'Northern red oak, birch and maple across the highland plateau, with rhododendron in the hollows.',
    why: 'Cool, wet highland climate at 1,000–1,500 m.',
    look: 'Brilliant autumn colour across a rolling plateau.',
    near: 'Whitlock, Lake Whitlock, Bald Rock.',
    memorable: 'October colour that draws crowds from the city.' },
  { id: 'lantern-red-spruce', name: 'Lantern Mountain Red Spruce', island: 'graystone', at: [63.6, 87.6], rx: 0.9, ry: 0.6, rot: 0, cover: 'spruce-fir', only: ['northern-hardwood', 'cove-hardwood', 'oak-hickory', 'spruce-fir'],
    desc: 'A small relict stand of red spruce on the cold north side of Lantern Mountain.',
    why: 'A cold, cloud-bathed north slope at the limit of spruce\'s range.',
    look: 'Dark spires among the hardwoods.',
    near: 'Lantern Mountain radar dome.',
    memorable: 'The southernmost spruce in the islands.' },
  { id: 'fallon-windshear', name: 'Fallon Cliff-Top Woods', island: 'graystone', at: [77.6, 84.0], rx: 1.0, ry: 3.0, rot: -20, cover: 'oak-hickory', only: NAT,
    desc: 'Stunted oaks and pines on the cliff tops, sheared flat and leaning landward by salt wind.',
    why: 'Constant onshore wind and salt spray.',
    look: 'Tree tops combed smooth and flat.',
    near: 'Fallon Cliffs, Coast Road, Cape Fallon.',
    memorable: 'Trees shaped like the wind.' },
  { id: 'grayback-glades', name: 'Grayback Granite Glades', island: 'graystone', at: [66.2, 73.6], rx: 1.4, ry: 1.2, rot: 0, cover: 'oak-hickory', only: NAT,
    desc: 'Outcrop vegetation on and around Grayback: mosses, lichens, red-stemmed succulents in the pools, and a fringe of red cedar.',
    why: 'Bare granite with thin soil islands.',
    look: 'Red and green carpets on grey rock in spring.',
    near: 'Grayback Mountain, Bright Water Road.',
    memorable: 'Tiny red plants in rain pools on bare rock.' },
  { id: 'wolfpen-laurel', name: 'Wolfpen Laurel Slopes', island: 'graystone', at: [50.6, 76.4], rx: 1.2, ry: 2.4, rot: 0, cover: 'cove-hardwood', only: NAT,
    desc: 'Dense laurel and rhododendron under oak on the slopes above Hollow Reach.',
    why: 'Steep, acidic, moist slopes.',
    look: 'Pink bloom above the gorge in June.',
    near: 'Wolfpen Mountain, Gate Shelf, Blue Wall Road.',
    memorable: 'Laurel blooming above the Gate Bridge.' },
  { id: 'bright-water-coves', name: 'Bright Water Coves', island: 'graystone', at: [68.4, 79.6], rx: 1.0, ry: 2.4, rot: 20, cover: 'cove-hardwood', only: NAT,
    desc: 'Rich cove forest along the Bright Water gorge with waterfalls and pools.',
    why: 'Sheltered gorge below the escarpment.',
    look: 'Green gorge with white water.',
    near: 'Bright Water River, Hornet Spire.',
    memorable: 'Swimming holes under cascades.' },
  { id: 'graystone-piedmont-pines', name: 'Graystone Piedmont Pines', island: 'graystone', at: [68.0, 72.0], rx: 3.0, ry: 1.6, rot: 20, cover: 'mixed-forest', only: NAT,
    desc: 'Loblolly pine and oak on the rolling hills below the Blue Wall, with old farm terraces and gullies.',
    why: 'Old fields on red clay abandoned and grown back in pine.',
    look: 'Pine forest with eroded red gullies.',
    near: 'Grayback, Bright Water, Graystone.',
    memorable: 'Stone walls and terraces in the woods.' },
  { id: 'frostcap-heath', name: 'Frostcap Heath', island: 'graystone', at: [68.4, 87.4], rx: 1.0, ry: 0.6, rot: 0, cover: 'heath-bald', only: NAT,
    desc: 'A heath bald of rhododendron and laurel on the frost-exposed summit.',
    why: 'Wind and ice keep trees from establishing.',
    look: 'Low, dense, dark shrubs on the summit.',
    near: 'Frostcap, Bright Water Lake.',
    memorable: 'Rime-coated rhododendron in winter.' },

  // ---------------------------------------------------------------- Bellamy
  { id: 'ocosta-bottoms', name: 'Ocosta River Bottoms', island: 'bellamy', at: [21.0, 34.0], rx: 1.0, ry: 5.0, rot: 0, cover: 'bottomland', only: NAT,
    desc: 'Floodplain forest of water oak, sweetgum, sycamore and cypress along the Ocosta, flooded each winter.',
    why: 'The river\'s floodplain floods regularly and stays fertile.',
    look: 'High-water marks on tree trunks.',
    near: 'Ocosta River, Moon Lake, Ox Lake.',
    memorable: 'Canoeing through flooded forest in February.' },
  { id: 'red-hills-pines', name: 'Red Hills Pine Woods', island: 'bellamy', at: [16.0, 48.0], rx: 4.0, ry: 1.8, rot: 10, cover: 'longleaf', only: NAT,
    desc: 'Open longleaf and shortleaf pine woods with wiregrass, burned every couple of years.',
    why: 'Well-drained sandy hills with regular fire.',
    look: 'Tall pines spaced widely over grass.',
    near: 'Iron Mountain, Sugarloaf Hill, Red Hills Road.',
    memorable: 'Smoke from spring burns drifting over the farms.' },
  { id: 'bay-rims', name: 'Bay Rim Pocosins', island: 'bellamy', at: [22.0, 32.0], rx: 6.0, ry: 2.0, rot: 0, cover: 'bay-forest', only: ['flatwoods', 'pine-plantation', 'bay-forest'],
    desc: 'Dense evergreen shrub bogs of bay, titi and gallberry around the Carolina bays.',
    why: 'Saturated, peaty soils around the bays.',
    look: 'Dark, glossy evergreen thickets.',
    near: 'Clearwater Bay, Tar Kiln Bay, Brown\'s Bay.',
    memorable: 'Impassable shrubs a few steps from open farmland.' },
  { id: 'sweetwater-swamp', name: 'Sweetwater Swamp', island: 'bellamy', at: [10.6, 36.6], rx: 1.8, ry: 0.6, rot: 0, cover: 'cypress-swamp', only: NAT,
    desc: 'A cypress and gum swamp along Sweetwater Creek.',
    why: 'Low, wet creek bottom near the coast.',
    look: 'Cypress knees in black water.',
    near: 'Sweetwater, Mirabel Sound.',
    memorable: 'Mist in the cypress at dawn.' },
  { id: 'bellamy-plantations', name: 'Bellamy Pine Plantations', island: 'bellamy', at: [14.0, 30.0], rx: 4.0, ry: 2.4, rot: 0, cover: 'pine-plantation', only: ['flatwoods', 'pine-plantation', 'pasture', 'cropland'],
    desc: 'Rows of slash and loblolly pine planted for pulpwood, at every stage from fresh clearcut to mature stand.',
    why: 'Poorly drained flatwoods are better for pine than for crops.',
    look: 'Straight rows of identical trees.',
    near: 'Dunmore, Bellamy Highway, Wickham Ferry.',
    memorable: 'Rows that flicker past the car window.' },
  { id: 'chalybeate-ravines', name: 'Chalybeate Ravines', island: 'bellamy', at: [10.4, 46.0], rx: 1.6, ry: 1.0, rot: 0, cover: 'mixed-forest', only: NAT,
    desc: 'Steep ravines in the Red Hills with beech, magnolia and iron-stained springs.',
    why: 'Streams cutting into the soft upland sediments.',
    look: 'Deep wooded ravines with orange seeps.',
    near: 'Harlow, Chalk Pits.',
    memorable: 'Rusty spring water staining the creek beds.' },

  // -------------------------------------------------------- Saint Ambrose
  { id: 'ambrose-maritime', name: 'Ambrose Maritime Forest', island: 'saint-ambrose', at: [44.0, 45.0], rx: 3.4, ry: 3.8, rot: 0, cover: 'maritime-forest', only: NAT,
    desc: 'Live oak, cabbage palm and magnolia hung with Spanish moss, with old dirt roads shaded into tunnels.',
    why: 'The old sea-island core, high and dry enough for hardwood forest.',
    look: 'Spanish moss and twisted live oaks.',
    near: 'Rice Hope, Cypress Pond, Haversham Regional Airport.',
    memorable: 'Driving through tunnels of moss-hung oaks.' },
  { id: 'kettle-pines', name: 'Kettle Island Pines', island: 'saint-ambrose', at: [49.0, 32.0], rx: 2.4, ry: 1.4, rot: 0, cover: 'flatwoods', only: NAT,
    desc: 'Slash pine and palmetto on the southern sea-island core.',
    why: 'Sandy, slightly lower ground than the main core.',
    look: 'Pines over palmetto.',
    near: 'Kettle, Kettle Shell Beach.',
    memorable: 'Palmetto rattling in the wind.' },
  { id: 'edgewater-hammocks', name: 'Edgewater Hammocks', island: 'saint-ambrose', at: [59.6, 48.2], rx: 1.8, ry: 1.6, rot: 0, cover: 'maritime-forest', only: NAT,
    desc: 'Live oak hammocks on Edgewater Island surrounded by marsh.',
    why: 'Islands of higher ground in the marsh.',
    look: 'Dark tree islands in tan marsh.',
    near: 'Edgewater, Heron Pond.',
    memorable: 'Tree islands floating on golden marsh.' },
  { id: 'bonnet-marsh-hammocks', name: 'Bonnet Marsh Hammocks', island: 'saint-ambrose', at: [64.0, 44.0], rx: 2.0, ry: 3.0, rot: 0, cover: 'maritime-forest', only: ['salt-marsh', 'fresh-marsh', 'maritime-forest', 'mixed-forest', 'pasture', 'cropland'],
    desc: 'Small palm and cedar hammocks scattered through the Bonnet River marsh.',
    why: 'Old shell middens and sand ridges in the marsh.',
    look: 'Palm islands in the marsh.',
    near: 'Bonnet River, Banks Highway.',
    memorable: 'Palms silhouetted against marsh sunsets.' },
  { id: 'haversham-oaks', name: 'Haversham Oak Avenue', island: 'saint-ambrose', at: [53.4, 49.4], rx: 0.5, ry: 0.9, rot: 0, cover: 'maritime-forest', only: NAT,
    desc: 'An avenue of huge live oaks leading from the town to an old house site.',
    why: 'Planted along an old road on the bluff.',
    look: 'Arched oak branches over a dirt road.',
    near: 'Haversham, Haversham River.',
    memorable: 'The arching canopy over the avenue.' },

  // ---------------------------------------------------------------- Wickham
  { id: 'sandhill-longleaf', name: 'Sandhill Longleaf Savanna', island: 'wickham', at: [13.4, 12.0], rx: 2.6, ry: 7.0, rot: 0, cover: 'longleaf', only: NAT,
    desc: 'Old-growth longleaf pine over wiregrass, with turkey oaks and gopher tortoise burrows, burned every few years.',
    why: 'Deep, dry sand on the relict dune ridge; regular fire.',
    look: 'Widely spaced pines over golden grass.',
    near: 'Scrub Hill, Blue Sink, Ridge Road.',
    memorable: 'Old pines with turpentine catface scars.' },
  { id: 'scrub-hill-scrub', name: 'Scrub Hill Scrub', island: 'wickham', at: [13.6, 14.4], rx: 1.0, ry: 1.6, rot: 0, cover: 'scrub', only: NAT,
    desc: 'Sand pine, scrub oaks and rosemary on bare white sand at the top of the ridge.',
    why: 'The driest, sandiest soil on the island.',
    look: 'Low, grey-green scrub on white sand.',
    near: 'Scrub Hill, Punchbowl Sink.',
    memorable: 'A desert landscape in a wet climate.' },
  { id: 'springs-hammock', name: 'Springs Hammock', island: 'wickham', at: [4.4, 14.4], rx: 2.0, ry: 3.4, rot: 0, cover: 'bottomland', only: NAT,
    desc: 'Hardwood hammock of live oak, magnolia, cabbage palm and southern red cedar around the springs and spring runs.',
    why: 'Moist, limestone-rich soils near the springs.',
    look: 'Dense, shady forest beside crystal-clear water.',
    near: 'Wickham Spring, Seacow Spring, Wickham.',
    memorable: 'Cool shade beside 22 °C spring water.' },
  { id: 'wickham-cypress-strand', name: 'Sawpit Cypress Strand', island: 'wickham', at: [18.4, 11.2], rx: 1.0, ry: 2.6, rot: 0, cover: 'cypress-swamp', only: NAT,
    desc: 'A long strand of cypress along the Sawpit River.',
    why: 'Drainage line through the eastern flatwoods.',
    look: 'Tall cypress along a creek.',
    near: 'Sawpit River, Gator Pond.',
    memorable: 'Cypress knees standing in clear water.' },
  { id: 'cedar-point-hammock', name: 'Cedar Point Hammock', island: 'wickham', at: [10.6, 1.8], rx: 1.4, ry: 0.8, rot: 0, cover: 'maritime-forest', only: NAT,
    desc: 'Southern red cedar and live oak on the shell ridge at Cedar Point.',
    why: 'Shell ridges on the coast support hardwood hammock.',
    look: 'Wind-twisted red cedars.',
    near: 'Cedar Shoals, Cedar Point Shell Beach.',
    memorable: 'Twisted cedars over white shell.' },

  // ------------------------------------------------------------ Ossahatchee
  { id: 'big-water-cypress', name: 'Big Water Cypress', island: 'ossahatchee', at: [40.6, 15.4], rx: 3.0, ry: 1.6, rot: 8, cover: 'cypress-swamp', only: ['cypress-swamp', 'fresh-marsh', 'bay-forest', 'flatwoods'],
    desc: 'Tall bald cypress hung with Spanish moss lining the Big Water channel, with ancient trees spared by loggers because they were hollow.',
    why: 'The deepest, permanently flooded part of the swamp.',
    look: 'Grey trunks and moss reflected in black water.',
    near: 'Big Water, Ossahatchee Skyway, Big Water tower.',
    memorable: 'Paddling among cypress older than the islands\' towns.' },
  { id: 'long-ridge-longleaf', name: 'Long Ridge Longleaf', island: 'ossahatchee', at: [60.0, 15.0], rx: 1.2, ry: 8.0, rot: -3, cover: 'longleaf', only: NAT,
    desc: 'Longleaf pine along the dry crest of Long Ridge.',
    why: 'Sandy relict barrier ridge, the only dry high ground on the island.',
    look: 'A line of tall pines above the swamp.',
    near: 'Highpine Knoll, Coastal Highway, Tarrow Landing.',
    memorable: 'A highway of dry pines beside a sea of swamp.' },
  { id: 'sill-bay-forest', name: 'Sill Bay Forest', island: 'ossahatchee', at: [52.0, 12.0], rx: 2.4, ry: 1.6, rot: 0, cover: 'bay-forest', only: ['cypress-swamp', 'fresh-marsh', 'bay-forest', 'flatwoods'],
    desc: 'Dense bay forest of loblolly bay, sweetbay and red bay on deep peat near the Sill Canal.',
    why: 'Peat that rarely floods deeply but never dries.',
    look: 'Glossy evergreen canopy.',
    near: 'Sill Lake, the Sill Canal.',
    memorable: 'The sweet smell of bay leaves.' },
  { id: 'tolar-cutover', name: 'Tolar Cutover', island: 'ossahatchee', at: [53.0, 19.6], rx: 2.0, ry: 1.0, rot: 0, cover: 'flatwoods', only: NAT,
    desc: 'Second-growth pine on a large pine island logged for the sawmill at Tolar, with sawdust piles and mill foundations.',
    why: 'A large island of sandy ground in the swamp.',
    look: 'Young pines among old mill ruins.',
    near: 'Tolar, the Trail.',
    memorable: 'Mounds of old sawdust still smoking after lightning strikes.' },
  { id: 'little-black-gum-swamp', name: 'Little Black Gum Swamp', island: 'ossahatchee', at: [31.0, 15.4], rx: 3.0, ry: 1.2, rot: 0, cover: 'cypress-swamp', only: ['cypress-swamp', 'fresh-marsh', 'bay-forest', 'flatwoods'],
    desc: 'Black gum and cypress along the Little Black River.',
    why: 'The river\'s floodplain through the western swamp.',
    look: 'Swollen gum trunks in dark water.',
    near: 'Little Black River, Black Lake, Dinner Pond.',
    memorable: 'Red gum leaves on black water in autumn.' },
  { id: 'sabal-coast-mangroves', name: 'Sabal Coast Mangroves', island: 'ossahatchee', at: [46.0, 5.6], rx: 8.0, ry: 0.9, rot: 0, cover: 'mangrove', only: ['salt-marsh', 'mangrove', 'fresh-marsh'],
    desc: 'Black mangrove thickets mixed with salt marsh along the south coast, with patches of grey dead mangroves killed by rare hard freezes.',
    why: 'The northern limit of mangroves: only the warmest, most sheltered shore supports them.',
    look: 'Dark green thickets with grey freeze-killed patches.',
    near: 'Sabal Landing, Sabal Bridges, Turtle Bay.',
    memorable: 'Grey skeletons of freeze-killed mangroves among living ones.' },

  // ------------------------------------------------- Mirabel, Banks, Calder
  { id: 'foreland-ridge-forest', name: 'Foreland Ridge Forest', island: 'mirabel', at: [2.4, 27.6], rx: 2.0, ry: 2.6, rot: 30, cover: 'maritime-forest', only: NAT,
    desc: 'Slash pine and live oak on the beach ridges of the Mirabel foreland, with marshy swales between.',
    why: 'Old beach ridges stable long enough to grow forest.',
    look: 'Parallel ridges of pine and marsh.',
    near: 'Dune lakes, Cape Serena Light.',
    memorable: 'Walking across rows of old shorelines.' },
  { id: 'serena-scrub', name: 'Serena Scrub', island: 'mirabel', at: [4.4, 33.4], rx: 0.8, ry: 1.6, rot: 0, cover: 'scrub', only: NAT,
    desc: 'Sand pine and rosemary scrub on old dunes south of Dunewood.',
    why: 'Old dunes too dry for other trees.',
    look: 'Grey-green scrub on white dunes.',
    near: 'Dunewood, Beach Road.',
    memorable: 'Rosemary scent on the dunes.' },
  { id: 'merrin-woods', name: 'Merrin Woods', island: 'gannet', at: [83.0, 9.2], rx: 1.2, ry: 0.8, rot: 40, cover: 'maritime-forest', only: NAT,
    desc: 'Maritime forest on the widest part of the cape: live oak, loblolly pine and dogwood among old dune ridges.',
    why: 'The only part of the Banks wide enough to shelter a forest from salt spray.',
    look: 'A dark green patch on a sand island.',
    near: 'Merrin, Merrin Woods Pond, Cape Merrin Light.',
    memorable: 'A forest in the middle of the ocean.' },
  { id: 'kestrel-thickets', name: 'Kestrel Thickets', island: 'gannet', at: [73.2, 24.6], rx: 0.6, ry: 1.6, rot: 30, cover: 'scrub', only: NAT,
    desc: 'Salt-pruned thickets of wax myrtle and yaupon behind the dunes.',
    why: 'Salt spray keeps woody plants low.',
    look: 'Dense low shrubs trimmed flat by the wind.',
    near: 'Kestrel Hill, Kestrel village.',
    memorable: 'Shrubs sculpted by the wind.' },
  { id: 'westside-park-woods', name: 'Westside Park Woods', island: 'calder', at: [31.8, 58.4], rx: 0.8, ry: 1.2, rot: 0, cover: 'park', only: ['urban', 'suburban', 'urban-core', 'park'],
    desc: 'The city\'s largest park: oak woods, lawns and the cypress lake on Calder\'s west shore.',
    why: 'Low, wet ground on the west shore left as parkland.',
    look: 'A green block against the grid.',
    near: 'Lake Ellery, Westside Park Beach.',
    memorable: 'Old oaks in the middle of the city.' },
];
