// Register: 50 lakes. Geometry lives in world/geography.mjs LAKES (same ids).

export const LAKE_TEXT = [
  // ---------------------------------------------------------------- Halcomb
  { id: 'calloway-lake', type: 'hydroelectric reservoir',
    where: 'Tennalee Cove, central Halcomb, behind Calloway Dam',
    desc: 'A long, branching reservoir that drowned the lower Tennalee Cove and the hollows around it. Arms of deep green water reach up every tributary valley; floating houseboats are moored in the sheltered coves.',
    why: 'A 135 m concrete dam in the narrow quartzite gorge below the cove stores the Tennalee for power and flood control.',
    look: 'Fjord-like, many-fingered outline under steep wooded slopes; a pale "bathtub ring" of bare clay shows when the water is drawn down in autumn.',
    near: 'Calloway Dam, Calloway village and marina, Cove Mountain, Huckleberry Knob, Upper Cove.',
    memorable: 'In late autumn the drawdown exposes old roadbeds, stone walls and chimneys from the drowned valley.' },
  { id: 'lake-hominy', type: 'water-supply reservoir',
    where: 'Hominy Creek valley north of Hominy',
    desc: 'A small reservoir with a grassy earth dam and a concrete spillway, surrounded by forest with no development on its shores.',
    why: 'Dams the narrow lower valley of Hominy Creek to supply Ledford and Hominy.',
    look: 'A narrow ribbon of water in a wooded valley.',
    near: 'Hominy, Chestnut Knob, Sugartree Knob, I-21.',
    memorable: 'The stepped spillway roars white after storms.' },
  { id: 'hickory-lake', type: 'plateau lake',
    where: 'Hickory Tableland, on Hickory Creek above Hickory Falls',
    desc: 'A tea-coloured lake on the flat plateau top, edged by sandstone ledges and stunted pine.',
    why: 'A low dam on Hickory Creek holds water on the impermeable sandstone caprock.',
    look: 'Dark water reflecting pale rock.',
    near: 'Hickory Falls, Hickory Knob, Hickory Flat.',
    memorable: 'Its outflow plunges off the escarpment a few hundred metres downstream.' },
  { id: 'sinking-pond', type: 'karst pond',
    where: 'Hickory Tableland near the airport',
    desc: 'A shallow pond that fills in winter and drains through its floor every summer, leaving a meadow of sedges.',
    why: 'Collapse into limestone beneath the thin sandstone cap.',
    look: 'Some years a lake, some years a meadow.',
    near: 'Hickory Tableland Airport, Lookout Bluff.',
    memorable: 'Its water disappears underground every summer.' },
  { id: 'blue-hole', type: 'karst spring pool',
    where: 'Coldwater Valley floor north of Coldwater',
    desc: 'A small, almost perfectly round spring pool of startlingly clear blue water, 22 m deep, overhung by sycamores.',
    why: 'Groundwater from the limestone valley rises through a solution shaft.',
    look: 'Electric blue water in a green pasture.',
    near: 'Coldwater River, Coldwater, the Old Valley Road.',
    memorable: 'You can see the bottom from the edge despite the depth.' },
  { id: 'coldwater-quarry-lake', type: 'flooded quarry',
    where: 'East side of the Coldwater Valley near the Narrows',
    desc: 'A water-filled limestone quarry with sheer grey walls and turquoise water.',
    why: 'An abandoned section of the limestone quarry filled with groundwater.',
    look: 'Turquoise water in a grey rock box.',
    near: 'Coldwater Limestone Quarry, I-21, Narrows Landing.',
    memorable: 'Its colour looks unreal next to the green valley.' },
  { id: 'gooseberry-pond', type: 'mountain bog pond',
    where: 'Beside Gooseberry Bald',
    desc: 'A tiny sphagnum bog pond surrounded by sedges, cranberry and stunted red maple.',
    why: 'A shallow hollow on the crest with impermeable soil.',
    look: 'Black water in a ring of bright moss.',
    near: 'Gooseberry Bald fire tower, the Parkway.',
    memorable: 'A bog at 1,300 m on a southern island.' },
  { id: 'big-laurel-millpond', type: 'millpond',
    where: 'Big Laurel Creek above Big Laurel village',
    desc: 'A small pond behind a dry-laid stone dam with the foundations of a mill at its foot.',
    why: 'An old dam built to power a sawmill on the only gentle reach of the creek.',
    look: 'Still water above a stone wall.',
    near: 'Big Laurel, Big Laurel Logging Grade.',
    memorable: 'The mill\'s iron water wheel lies rusting below the dam.' },

  // -------------------------------------------------------------- Graystone
  { id: 'lake-whitlock', type: 'highland reservoir',
    where: 'Whitlock Basin on the Graystone highlands',
    desc: 'A clear mountain lake held by a low stone dam on the upper Thunderhole, with summer houses, boathouses and a stone pavilion along its shore.',
    why: 'A low dam at the outlet of the highland basin holds back the upper Thunderhole.',
    look: 'Still water reflecting Whitlock Mountain\'s granite face.',
    near: 'Whitlock village, Whitlock Mountain, the Highlands Road.',
    memorable: 'Mirror reflections of granite and fall colour at dawn.' },
  { id: 'bright-water-lake', type: 'highland lake',
    where: 'Headwaters of the Bright Water River',
    desc: 'A small lake in a hollow on the plateau, ringed by rhododendron.',
    why: 'Water ponded behind a granite sill at the head of the Bright Water.',
    look: 'Dark water edged by pink rhododendron in June.',
    near: 'Frostcap, Lantern Mountain, Highlands Road.',
    memorable: 'The outflow pours over the granite sill into the gorge.' },
  { id: 'fallon-reservoir', type: 'water-supply reservoir',
    where: 'Upper Fallon River valley',
    desc: 'A narrow reservoir in a steep valley with a concrete arch dam.',
    why: 'Water supply for Fallon, built where the valley narrows between granite walls.',
    look: 'A thin curved dam between cliffs.',
    near: 'Fallon, Ravenrock, Highlands Road.',
    memorable: 'The curved dam is barely 20 m wide at its crest.' },
  { id: 'cutstone-quarry', type: 'flooded quarry',
    where: 'Cutstone Mountain west of Graystone town',
    desc: 'A deep, emerald-green flooded pit with terraced granite benches, rusted derrick footings and cables.',
    why: 'The lowest bench of the granite quarry filled with water after pumping stopped.',
    look: 'Emerald water in a grey stepped bowl.',
    near: 'Cutstone, Cutstone Quarry, Blue Wall Incline.',
    memorable: 'Old derrick masts still stand on the rim.' },

  // -------------------------------------------------------- Calder / Corliss
  { id: 'heights-reservoir', type: 'city reservoir',
    where: 'Top of Calder Heights',
    desc: 'A rectangular stone-lined reservoir on the summit of the Heights, surrounded by a jogging path and a wrought-iron fence.',
    why: 'Built on the highest ground in the city to give gravity pressure to the water mains.',
    look: 'A rectangle of water ringed by city lights.',
    near: 'Calder Heights broadcast tower, the Heights district.',
    memorable: 'The skyline reflected in still water at dusk.' },
  { id: 'lake-ellery', type: 'park lake',
    where: 'Westside Park, Calder',
    desc: 'A curving park lake with stone bridges, a boathouse and islands of bald cypress.',
    why: 'A former tidal creek mouth on the west shore dammed and landscaped into a park.',
    look: 'Cypress knees in still water with towers behind.',
    near: 'Westside, Calder Yacht Basin.',
    memorable: 'The city\'s only swamp, planted with cypress a century ago.' },
  { id: 'corliss-cooling-pond', type: 'industrial cooling pond',
    where: 'East Corliss beside the generating station',
    desc: 'A long rectangular pond of warm water that steams on cold mornings.',
    why: 'Cooling water for the generating station\'s condensers.',
    look: 'A steaming pond under smokestacks.',
    near: 'Corliss Generating Station, Corliss Landfill Hill.',
    memorable: 'Winter mornings the pond is wrapped in its own fog.' },

  // ---------------------------------------------------------------- Bellamy
  { id: 'lake-ocosta', type: 'river reservoir',
    where: 'Ocosta River north of Bellamy',
    desc: 'A narrow, winding reservoir in the Ocosta valley with an earth dam and a water-treatment plant.',
    why: 'The upper Ocosta was dammed to supply Bellamy and Bellamy Bluffs.',
    look: 'A narrow ribbon of water between red-clay bluffs.',
    near: 'Sugarloaf Hill, Bellamy Solar Farm, Red Hills Road.',
    memorable: 'Red clay bluffs reflected in brown water.' },
  { id: 'clearwater-bay', type: 'Carolina bay lake',
    where: 'Southern flatwoods of Bellamy',
    desc: 'The largest of the oval bay lakes: shallow, clear, with a white sand bottom and a sand rim on its south-east shore, surrounded by bay forest and cypress.',
    why: 'One of the elliptical depressions that dot the coastal plain, all aligned north-west to south-east.',
    look: 'A perfect ellipse from the air, white sand under tea-coloured water.',
    near: 'Ocosta River, Ocosta Nuclear Station, Moon Lake.',
    memorable: 'Wading out a hundred metres and still knee-deep on white sand.' },
  { id: 'tar-kiln-bay', type: 'Carolina bay lake',
    where: 'Southern Bellamy west of Ocosta',
    desc: 'A dark-water bay lake ringed by pocosin, with remains of a tar kiln mound on its sand rim.',
    why: 'Carolina bay depression in the flatwoods.',
    look: 'A dark oval in a ring of dense green shrubs.',
    near: 'Ocosta, Dunmore, Bellamy Highway.',
    memorable: 'The blackened kiln mound on the rim.' },
  { id: 'browns-bay', type: 'Carolina bay lake',
    where: 'East-central Bellamy',
    desc: 'A small bay lake with cypress fringing its shallow north-west end.',
    why: 'Carolina bay depression.',
    look: 'Oval lake with a fringe of cypress.',
    near: 'Bellamy County Landfill, Black Creek.',
    memorable: 'Its cypress fringe glows rust-red in November.' },
  { id: 'little-bay', type: 'Carolina bay lake',
    where: 'Southern Bellamy near Dunmore',
    desc: 'A small, almost-filled bay with open water only in its centre.',
    why: 'A bay being slowly filled by peat.',
    look: 'Open water inside a ring of marsh.',
    near: 'Dunmore, Tar Kiln Bay.',
    memorable: 'You can see the whole cycle of a bay filling in.' },
  { id: 'sand-bay', type: 'Carolina bay lake',
    where: 'South-western Bellamy',
    desc: 'A shallow bay with a high white sand rim used as a swimming beach.',
    why: 'Carolina bay with a well-developed sand rim.',
    look: 'White sand rim on one side.',
    near: 'Sweetwater, Bellamy Highway.',
    memorable: 'A beach in the middle of farmland.' },
  { id: 'moon-lake', type: 'oxbow lake',
    where: 'Ocosta floodplain south of Bellamy',
    desc: 'A crescent oxbow of the Ocosta, choked with water lilies and cypress.',
    why: 'An abandoned meander loop cut off by the river.',
    look: 'A perfect crescent.',
    near: 'Ocosta River, Ocosta River Road.',
    memorable: 'Seen from the air, a crescent moon in the forest.' },
  { id: 'ox-lake', type: 'oxbow lake',
    where: 'Lower Ocosta floodplain',
    desc: 'A narrow oxbow with standing dead cypress.',
    why: 'Abandoned meander of the Ocosta.',
    look: 'Grey snags in a crescent of water.',
    near: 'Ocosta, Ocosta estuary.',
    memorable: 'Herons nest in the dead cypress.' },
  { id: 'chalk-pits', type: 'kaolin pit lakes',
    where: 'Red Hills near Harlow',
    desc: 'A string of flooded kaolin pits with milky turquoise water and chalk-white banks.',
    why: 'Kaolin clay mined where the old upland sands contain thick clay lenses.',
    look: 'Bright white banks around chalky blue water.',
    near: 'Harlow, Iron Mountain, Red Hills Road.',
    memorable: 'White cliffs in red-clay country.' },

  // ---------------------------------------------------------------- Mirabel
  { id: 'cypress-dune-lake', type: 'coastal dune lake',
    where: 'Mirabel foreland near the Gulf beach',
    desc: 'A long, narrow freshwater lake in a swale between beach ridges, ringed by cypress and slash pine.',
    why: 'Fresh water ponded in the swales of the beach-ridge plain; storms occasionally open an outfall to the bay.',
    look: 'Dark fresh water a few steps from white sand.',
    near: 'Dune Lakes Beach, Mirabel–Serena foreland.',
    memorable: 'Fresh and salt water within sight of each other.' },
  { id: 'little-serena-lake', type: 'coastal dune lake',
    where: 'Northern Mirabel foreland',
    desc: 'A narrow swale lake bordered by marsh and pine.',
    why: 'Swale between beach ridges.',
    look: 'Long sliver of water between pine ridges.',
    near: 'Port Serena, Beach Road.',
    memorable: 'Mirror-flat water at dawn.' },
  { id: 'long-swale-lake', type: 'coastal dune lake',
    where: 'Southern Mirabel foreland',
    desc: 'The longest swale lake, curving parallel to the coast.',
    why: 'Follows an old shoreline.',
    look: 'A curving ribbon of water.',
    near: 'Cape Serena Light, Beach Road.',
    memorable: 'It traces the shape of an ancient beach.' },
  { id: 'oyster-dune-lake', type: 'coastal dune lake',
    where: 'Mirabel foreland near the lagoon',
    desc: 'A small brackish swale lake with oyster shell on its bottom.',
    why: 'A swale lake that occasionally connects to the lagoon.',
    look: 'Grey-green water with shell beaches.',
    near: 'Port Serena, Mirabel Sound.',
    memorable: 'Oyster shells in a pond.' },
  { id: 'lake-mirabel', type: 'resort lake',
    where: 'Golf course in central Mirabel Beach',
    desc: 'An artificial lake with fountains surrounded by golf greens and condominiums.',
    why: 'Excavated for stormwater and fill during resort construction.',
    look: 'Fountains and putting greens.',
    near: 'Mirabel Beach, Beach Road.',
    memorable: 'Alligators sunning beside the 7th green.' },

  // ---------------------------------------------------------------- Wickham
  { id: 'blue-sink', type: 'sinkhole lake',
    where: 'West flank of the Sandhill Ridge',
    desc: 'A round, deep sinkhole lake of clear blue water in a ring of longleaf pine.',
    why: 'Collapse of the limestone beneath the sand ridge into an underground cave system.',
    look: 'A circle of deep blue in pale sand.',
    near: 'Scrub Hill, Turpentine Tram grade, Wickham Spring.',
    memorable: 'Cave divers enter the aquifer through its floor.' },
  { id: 'punchbowl-sink', type: 'sinkhole',
    where: 'Near Scrub Hill',
    desc: 'A steep-walled sinkhole with ferns and dripping limestone walls around a small pool 30 m below the rim.',
    why: 'Recent collapse into the aquifer.',
    look: 'A green funnel in the scrub.',
    near: 'Scrub Hill fire tower, Ridge Road.',
    memorable: 'Ten degrees cooler at the bottom than at the rim.' },
  { id: 'round-lake', type: 'sinkhole lake',
    where: 'East flank of the Sandhill Ridge',
    desc: 'A circular lake with a white sand shoreline and longleaf to the water\'s edge.',
    why: 'Old sinkhole partly filled with sand.',
    look: 'A round lake with white beaches.',
    near: 'Gator Pond, Ridge Road.',
    memorable: 'Perfectly round from the fire tower.' },
  { id: 'deep-lake', type: 'sinkhole lake',
    where: 'South of Blue Sink',
    desc: 'A small, very deep lake with steep sides and dark water.',
    why: 'Deep solution sinkhole.',
    look: 'Dark water in a steep basin.',
    near: 'Fire Tower Hill, Little Sink.',
    memorable: 'Its water is cold even in August.' },
  { id: 'sand-lake', type: 'sinkhole lake',
    where: 'Southern Wickham near the ridge',
    desc: 'A broad, shallow lake with wide white sand beaches.',
    why: 'Coalesced shallow sinkholes on the ridge flank.',
    look: 'White sand and pale water.',
    near: 'Phosphate Pits, Fire Tower Hill.',
    memorable: 'The widest beach on Wickham is on a lake.' },
  { id: 'little-sink', type: 'sinkhole pond',
    where: 'South end of the Sandhill Ridge',
    desc: 'A tiny sinkhole pond in the scrub.',
    why: 'Small collapse sinkhole.',
    look: 'A pocket of water in dense scrub.',
    near: 'Fire Tower Hill, Cedar Shoals road.',
    memorable: 'Easy to walk past without seeing.' },
  { id: 'gator-pond', type: 'flatwoods pond',
    where: 'Eastern Wickham flatwoods',
    desc: 'A shallow marshy pond with lily pads and a resident population of alligators.',
    why: 'Wet depression in the poorly drained flatwoods.',
    look: 'Lily pads and eyes in the water.',
    near: 'Round Lake, the Trail.',
    memorable: 'The alligators are the reason for the name.' },
  { id: 'phosphate-pits', type: 'flooded mine pits',
    where: 'South-eastern Wickham',
    desc: 'A row of long, straight-sided water-filled trenches with spoil ridges between them.',
    why: 'Abandoned phosphate mining in the limestone.',
    look: 'Parallel strips of water from the air.',
    near: 'Sand Lake, Hurricane Beach.',
    memorable: 'Geometric scars in the wilderness.' },

  // ------------------------------------------------------------ Ossahatchee
  { id: 'big-water', type: 'swamp lake',
    where: 'Central Ossahatchee swamp south of the Trail',
    desc: 'A long, narrow lake of tea-coloured water lined with cypress and hanging moss.',
    why: 'A deep channel in the peat where water moves slowly west.',
    look: 'A dark ribbon through cypress.',
    near: 'Ossahatchee Skyway, Big Water observation tower.',
    memorable: 'The water is so dark it reflects like a mirror.' },
  { id: 'cowhouse-lake', type: 'swamp lake',
    where: 'Central swamp',
    desc: 'An open lake surrounded by wet prairie.',
    why: 'A low point in the peat surface.',
    look: 'Open water in a sea of grass.',
    near: 'Sill Lake, Cypress Tram grade.',
    memorable: 'One of the few open horizons in the swamp.' },
  { id: 'sill-lake', type: 'swamp lake',
    where: 'Eastern swamp near the Sill Canal',
    desc: 'A small lake at the end of an abandoned straight canal.',
    why: 'Ponded where the canal spoil blocked drainage.',
    look: 'A lake at the end of a ruler-straight canal.',
    near: 'The Sill Canal, Long Ridge.',
    memorable: 'The canal points straight at it.' },
  { id: 'dinner-pond', type: 'swamp pond',
    where: 'Western swamp',
    desc: 'A small pond in the cypress with a fishing platform.',
    why: 'Gator hole kept open in the peat.',
    look: 'A clearing of water in cypress.',
    near: 'Little Black River.',
    memorable: 'A favourite fishing spot.' },
  { id: 'honey-lake', type: 'swamp lake',
    where: 'Northern swamp edge',
    desc: 'A lake surrounded by tupelo trees.',
    why: 'Wet hollow at the swamp margin.',
    look: 'Tupelo trees standing in water.',
    near: 'The Trail.',
    memorable: 'Bee hives on platforms along its shore.' },
  { id: 'black-lake', type: 'swamp lake',
    where: 'South-western swamp',
    desc: 'The darkest lake in the swamp.',
    why: 'Deep peat-stained water.',
    look: 'Ink-black water.',
    near: 'Little Black River, Wickham shore.',
    memorable: 'Visibility a few centimetres.' },
  { id: 'long-ridge-pond', type: 'sinkhole pond',
    where: 'On Long Ridge',
    desc: 'A small, clear sinkhole pond among longleaf pines.',
    why: 'Collapse through the dune ridge into limestone.',
    look: 'Clear water in white sand.',
    near: 'Highpine Knoll, Coastal Highway.',
    memorable: 'Clear water on the edge of a black-water swamp.' },
  { id: 'borrow-pit-lake', type: 'borrow pit',
    where: 'Along the Trail',
    desc: 'A long, straight pond beside the highway.',
    why: 'Dug to provide fill for the road causeway.',
    look: 'A straight ribbon of water beside the road.',
    near: 'The Trail, Tolar.',
    memorable: 'Alligators lining the bank beside traffic.' },

  // -------------------------------------------------------- Saint Ambrose
  { id: 'rice-reserve', type: 'old rice reserve',
    where: 'Central Saint Ambrose near Rice Hope',
    desc: 'A freshwater impoundment held by earthen dikes with wooden trunk gates.',
    why: 'Built to store fresh water for flooding rice fields.',
    look: 'Square-edged water with dikes.',
    near: 'Rice Hope, Rice Hope Road.',
    memorable: 'Wooden trunk gates still control the water.' },
  { id: 'cypress-pond', type: 'pond',
    where: 'Ambrose Main core',
    desc: 'A small cypress pond in the live-oak forest.',
    why: 'Fresh water ponded in a hollow of the sea-island core.',
    look: 'Cypress in still water.',
    near: 'Ambrose Maritime Forest.',
    memorable: 'Wood storks wade its edges.' },
  { id: 'heron-pond', type: 'impoundment',
    where: 'Edgewater Island',
    desc: 'A diked brackish pond used by wading birds.',
    why: 'Old impoundment on the marsh edge.',
    look: 'Bird-filled shallows.',
    near: 'Edgewater, Haversham River.',
    memorable: 'Hundreds of herons at dusk.' },

  // ----------------------------------------------------- Banks and keys
  { id: 'merrin-woods-pond', type: 'freshwater pond',
    where: 'Merrin Woods, Cape Merrin',
    desc: 'A small freshwater pond in the maritime forest, among dune ridges.',
    why: 'Fresh water perched in the dune swales of the cape.',
    look: 'Fresh water under live oaks.',
    near: 'Merrin, Cape Merrin Light.',
    memorable: 'A freshwater pond on a sand island.' },
  { id: 'sabal-salt-pond', type: 'salt pond',
    where: 'Sabal Key',
    desc: 'A shallow, hypersaline pond that turns pink in summer.',
    why: 'Evaporation pond on the low centre of the key.',
    look: 'Pink water.',
    near: 'Sabal village, Sabal Key beach.',
    memorable: 'Its summer colour.' },
];
