// Register: 100 named landmarks in four visibility tiers.
//   primary   — visible from many kilometres (skyline, towers, bridges, peaks)
//   secondary — visible from several kilometres
//   local     — seen from nearby roads and trails
//   micro     — small details found while exploring
// `kind` and `h` (height above ground, m) drive the explorer's markers.

export const LANDMARKS = [
  // ================================================================ PRIMARY
  { id: 'ledford-dome-tower', name: 'Ledford Dome Tower', island: 'halcomb', at: [29.0, 80.3], tier: 'primary', kind: 'tower', h: 14,
    desc: 'A concrete observation tower with a spiral ramp on the highest summit in the islands, rising just above the spruce–fir canopy.',
    why: 'Built where the archipelago\'s highest point is hidden by trees.',
    look: 'A pale disc on a ramp, on top of a black conifer dome.',
    near: 'Ledford Dome Road, Ledford Spruce–Fir Forest, Ledford Gap.',
    memorable: 'The point from which every other landmark in the islands can be seen.' },
  { id: 'callahan-north-face', name: 'Callahan North Face', island: 'halcomb', at: [33.0, 85.4], tier: 'primary', kind: 'cliff', h: 0,
    desc: 'The 1,900 m north face of Mount Callahan rising from the Narrows, with pale slate cliffs in its upper third.',
    why: 'The strait has cut into the base of the steepest mountain front in the islands.',
    look: 'A wall of forest and rock filling the view from the mainland.',
    near: 'Mount Callahan, Narrows Road, Big Laurel.',
    memorable: 'Snow and rime on its cliffs above a sea strait.' },
  { id: 'calder-tower', name: 'Calder Tower', island: 'calder', at: [37.8, 61.8], tier: 'primary', kind: 'skyscraper', h: 268,
    desc: 'A 64-storey glass tower with a stepped crown and a lit spire, the tallest building in the islands.',
    why: 'Built on the bedrock bluff at the heart of Downtown.',
    look: 'Blue-green glass by day, a white lit crown by night.',
    near: 'Downtown, Old Market, Calder Central.',
    memorable: 'Visible from the Ledford Dome tower 22 km away.' },
  { id: 'gate-bridge', name: 'Gate Bridge', island: 'graystone', at: [46.05, 77.05], tier: 'primary', kind: 'bridge', h: 120,
    desc: 'A suspension bridge with a 1,020 m main span strung between cliff-top towers, its deck 190 m above Hollow Reach. On the Halcomb side the road leaves the Bearpen Tunnel straight onto the bridge.',
    why: 'The narrowest point of the drowned gorge, with rock both sides.',
    look: 'Two grey towers and a thin deck between granite walls.',
    near: 'Bearpen Tunnel, Veil Falls, Gate Shelf, Blue Wall Road.',
    memorable: 'Cars emerging from a tunnel directly onto a bridge in the sky.' },
  { id: 'grayback-dome', name: 'Grayback Mountain', island: 'graystone', at: [66.2, 73.6], tier: 'primary', kind: 'dome', h: 0,
    desc: 'A bare granite dome rising 380 m out of the farmland of the Piedmont strip.',
    why: 'A resistant granite pluton.',
    look: 'Grey whaleback against the green.',
    near: 'Graystone, Bright Water, Grayback Glades.',
    memorable: 'The island is named after it.' },
  { id: 'lantern-radar', name: 'Lantern Mountain Radar Dome', island: 'graystone', at: [63.5, 87.4], tier: 'primary', kind: 'radome', h: 40,
    desc: 'A white air-traffic radar dome and lit tower on the second-highest summit of Graystone.',
    why: 'Clear radar coverage over the sea and all the islands.',
    look: 'A white golf ball on the skyline.',
    near: 'Lantern Mountain, Highlands Road.',
    memorable: 'Its red lights pulse over the north coast at night.' },
  { id: 'corliss-stacks', name: 'Corliss Stacks', island: 'corliss', at: [53.6, 57.4], tier: 'primary', kind: 'stacks', h: 180,
    desc: 'Two 180 m concrete chimneys of the old coal units at the Corliss Generating Station, with red-and-white bands near the top.',
    why: 'Tall stacks to disperse smoke over the sound, beside the cooling water.',
    look: 'Twin banded chimneys above the port.',
    near: 'Corliss Generating Station, Cooling Pond, Landfill Hill.',
    memorable: 'Seen from Graystone, Saint Ambrose and Calder alike.' },
  { id: 'ocosta-cooling-towers', name: 'Ocosta Cooling Towers', island: 'bellamy', at: [24.6, 27.6], tier: 'primary', kind: 'cooling-towers', h: 165,
    desc: 'Two hyperbolic concrete cooling towers of the nuclear station, usually trailing white plumes.',
    why: 'Cooling water from Ketch Sound and the flat, stable ground of south Bellamy.',
    look: 'Two hourglass towers and their steam clouds.',
    near: 'Ocosta Nuclear Station, Clearwater Bay, Ocosta estuary.',
    memorable: 'The plumes are visible from Wickham, Ossahatchee and Mirabel.' },
  { id: 'wcdr-mast', name: 'WCDR-TV Mast', island: 'bellamy', at: [22.6, 43.0], tier: 'primary', kind: 'mast', h: 518,
    desc: 'A guyed television mast 518 m tall, the tallest structure in the islands, with banks of red lights.',
    why: 'Flat farmland lets a single tall mast cover all the islands.',
    look: 'A needle on the horizon with blinking red lights.',
    near: 'Bellamy Solar Farm, Lake Ocosta.',
    memorable: 'Its lights are visible from nearly everywhere at night.' },
  { id: 'cape-merrin-light', name: 'Cape Merrin Lighthouse', island: 'gannet', at: [84.2, 8.7], tier: 'primary', kind: 'lighthouse', h: 60,
    desc: 'A brick lighthouse 60 m tall painted in a diagonal black-and-white checkerboard, the tallest light on the coast.',
    why: 'Marks the cape and the long Merrin Shoals extending offshore.',
    look: 'Checkered tower above the maritime forest.',
    near: 'Merrin Woods, Lighthouse Beach, Merrin.',
    memorable: 'Its beam sweeps over the breakers on the shoals.' },
  { id: 'merrin-wind-farm', name: 'Merrin Shoals Wind Farm', island: 'gannet', at: [93.0, 14.0], tier: 'primary', kind: 'wind-farm', h: 230,
    desc: 'Twenty-eight offshore wind turbines in rows on the shallow shoals east of the Banks.',
    why: 'Shallow water and steady wind on the shoals.',
    look: 'White turbines on the ocean horizon.',
    near: 'Merrin Shoals, Cape Merrin Light.',
    memorable: 'Red lights blinking in unison at night.' },
  { id: 'calloway-dam', name: 'Calloway Dam', island: 'halcomb', at: [35.0, 70.35], tier: 'primary', kind: 'dam', h: 135,
    desc: 'A 135 m concrete gravity dam in the quartzite gorge below Tennalee Cove, with a road across its crest and a powerhouse at its foot.',
    why: 'The gorge narrows between quartzite ridges here, the cheapest place to hold back the river.',
    look: 'A pale concrete wall between wooded ridges.',
    near: 'Calloway Lake, Hogback, Calloway Dam Road.',
    memorable: 'Standing on the crest with lake on one side and gorge on the other.' },
  { id: 'long-bridge', name: 'Long Bridge', island: 'bellamy', at: [34.0, 53.8], tier: 'primary', kind: 'bridge', h: 45,
    desc: 'A low concrete trestle carrying I-21 across the sound to Bellamy, rising to a high navigation hump in the middle.',
    why: 'The shortest crossing from Calder to the flat land for the airport.',
    look: 'A long line on the water with a hump.',
    near: 'Bellamy Bluffs, South Shore, Ashwood River mouth.',
    memorable: 'The hump framing the skyline.' },
  { id: 'narrows-bridge', name: 'Narrows Bridge', island: 'halcomb', at: [12.1, 91.5], tier: 'primary', kind: 'bridge', h: 60,
    desc: 'A steel cantilever truss carrying I-21 from the mainland across the narrowest point of the Narrows.',
    why: 'The Narrows is narrowest where the Coldwater Valley meets the strait.',
    look: 'Black steel truss against the North Face.',
    near: 'Narrows Landing, Narrows Rail Bridge, Narrows crossing towers.',
    memorable: 'The gateway to the islands.' },
  { id: 'blue-wall', name: 'The Blue Wall', island: 'graystone', at: [61.0, 78.4], tier: 'primary', kind: 'escarpment', h: 0,
    desc: 'The escarpment along the south-east side of the Graystone highlands, falling 800 m in two kilometres, streaked with waterfalls.',
    why: 'The edge of the uplifted highland block, being worn back by the rain-soaked streams.',
    look: 'A blue-hazed wall across the island.',
    near: 'Glassface Dome, Pale Wall, Thunderhole Falls, Anvil Rock.',
    memorable: 'Seen from Calder as a blue rampart behind Graystone.' },
  { id: 'fallon-cliffs', name: 'Fallon Cliffs', island: 'graystone', at: [77.3, 83.4], tier: 'primary', kind: 'cliffs', h: 0,
    desc: 'Granite sea cliffs up to 250 m high along Graystone\'s east coast, with the Coast Road running along the top.',
    why: 'The highlands meet the open Atlantic and the waves undercut them.',
    look: 'Pink-grey walls rising out of the surf.',
    near: 'Coast Road, Fallon, Cape Fallon Light.',
    memorable: 'Breakers exploding at the foot of the cliffs.' },
  { id: 'corliss-cranes', name: 'Corliss Gantry Cranes', island: 'corliss', at: [52.0, 61.4], tier: 'primary', kind: 'cranes', h: 75,
    desc: 'Eight ship-to-shore container cranes lined along the berth, their booms raised when idle.',
    why: 'Deep berth beside the ship channel.',
    look: 'Red and white cranes like giant animals.',
    near: 'Container Terminal, I-121.',
    memorable: 'Raised booms silhouetted at sunset.' },
  { id: 'calder-heights-tower', name: 'Calder Heights Tower', island: 'calder', at: [35.5, 58.6], tier: 'primary', kind: 'mast', h: 210,
    desc: 'A self-supporting broadcast tower on the summit of Calder Heights.',
    why: 'The highest ground in the city.',
    look: 'A lattice tower above the reservoir.',
    near: 'Heights Reservoir, The Heights.',
    memorable: 'Lit in different colours for holidays.' },
  { id: 'mirabel-sands-tower', name: 'Mirabel Sands', island: 'mirabel', at: [4.9, 44.2], tier: 'primary', kind: 'skyscraper', h: 95,
    desc: 'The tallest condominium tower on the barrier island, white with curved balconies.',
    why: 'Beachfront at the widest part of the island.',
    look: 'A white slab above the strip.',
    near: 'Condo Row, Mirabel Beach.',
    memorable: 'It glows pink at sunset.' },
  { id: 'narrows-crossing-towers', name: 'Narrows Crossing Towers', island: 'halcomb', at: [13.6, 90.6], tier: 'primary', kind: 'pylons', h: 150,
    desc: 'A pair of 150 m transmission towers carrying high-voltage lines across the Narrows.',
    why: 'The power line from the mainland must clear shipping in the strait.',
    look: 'Red-and-white towers with wires sagging across the water.',
    near: 'Narrows Bridge, Narrows Substation.',
    memorable: 'Wires humming over the strait.' },
  { id: 'tennalee-river-bridge', name: 'Tennalee River Bridge', island: 'calder', at: [33.75, 63.5], tier: 'primary', kind: 'bridge', h: 30,
    desc: 'The interstate bridge from Halcomb into Calder across the North Channel.',
    why: 'The shortest crossing west of Downtown.',
    look: 'A long concrete arc above the channel.',
    near: 'Uptown, Halcomb Heights, Northpoint.',
    memorable: 'Where the skyline first appears.' },
  { id: 'kestrel-hill-dune', name: 'Kestrel Hill Dune', island: 'gannet', at: [73.3, 23.9], tier: 'primary', kind: 'dune', h: 0,
    desc: 'A 28 m bare migrating sand dune.',
    why: 'Wind-blown sand piles up where the barrier is widest.',
    look: 'A white hill on a flat island.',
    near: 'Kestrel, Kestrel Beach.',
    memorable: 'Visible from the inlet bridges and from boats offshore.' },

  // ============================================================== SECONDARY
  { id: 'veil-falls', name: 'Veil Falls', island: 'graystone', at: [48.8, 81.0], tier: 'secondary', kind: 'waterfall', h: 130,
    desc: 'Hollow Creek leaps 130 m from the rim of Hollow Reach straight into the sea, spreading into spray.',
    why: 'The creek has not cut down as fast as the drowned gorge, so it falls from a hanging valley.',
    look: 'A white veil on a dark granite wall.',
    near: 'Veil Falls Shingle, Gate Bridge, Hawkbill Knob.',
    memorable: 'Visible from the Gate Bridge deck four kilometres away.' },
  { id: 'thunderhole-falls', name: 'Thunderhole Falls', island: 'graystone', at: [60.7, 77.8], tier: 'secondary', kind: 'waterfall', h: 120,
    desc: 'The Thunderhole River drops 120 m in a series of falls through a slot in the Blue Wall.',
    why: 'The river crosses the escarpment in a narrow gorge.',
    look: 'White water in a dark slot.',
    near: 'Thunderhole Gorge, Thunderhole Overlook.',
    memorable: 'Its roar can be heard from the Whitlock Grade.' },
  { id: 'hickory-falls', name: 'Hickory Falls', island: 'halcomb', at: [8.7, 80.85], tier: 'secondary', kind: 'waterfall', h: 80,
    desc: 'An 80 m free-falling waterfall where Hickory Creek leaves the Tableland.',
    why: 'The creek flows over the hard sandstone caprock and falls where it ends.',
    look: 'A thin plunge into a deep amphitheatre.',
    near: 'Hickory Lake, Hickory Falls Overlook.',
    memorable: 'Behind the falls is a rock shelter you can walk into.' },
  { id: 'piney-falls', name: 'Piney Falls', island: 'halcomb', at: [4.55, 73.75], tier: 'secondary', kind: 'waterfall', h: 85,
    desc: 'Piney Creek falls 85 m from the Tableland Bluffs onto the cobbles of Piney Cove.',
    why: 'The sea is cutting the bluffs back faster than the creek can cut down.',
    look: 'A white thread on the cliffs above the bay.',
    near: 'Piney Cove, Lookout Bluff.',
    memorable: 'Seen from boats on Serena Bay.' },
  { id: 'tennalee-falls', name: 'Tennalee Falls', island: 'halcomb', at: [36.9, 66.1], tier: 'secondary', kind: 'waterfall', h: 22,
    desc: 'A broad series of granite ledges where the Tennalee drops into tidewater, between brick mill buildings.',
    why: 'The fall line, where hard crystalline rock meets softer coastal sediments.',
    look: 'Wide white water between brick walls.',
    near: 'Mill District, Tennalee Water Works.',
    memorable: 'Kayakers playing in the standing waves below the mills.' },
  { id: 'calder-central-clock', name: 'Calder Central Clock Tower', island: 'calder', at: [37.2, 61.6], tier: 'secondary', kind: 'clock-tower', h: 70,
    desc: 'The granite clock tower of the main railroad station.',
    why: 'The passenger railroad\'s terminus.',
    look: 'A stone campanile with a lit clock face.',
    near: 'Station Square, Market Street Bridge.',
    memorable: 'Its chimes heard across Downtown.' },
  { id: 'market-street-bridge', name: 'Market Street Bridge', island: 'calder', at: [37.25, 63.6], tier: 'secondary', kind: 'lift-bridge', h: 55,
    desc: 'A double-deck vertical lift bridge with tall steel towers, carrying road on top and rail beneath.',
    why: 'Barges must pass up the river to Tennalee Falls.',
    look: 'Two steel towers lifting a span.',
    near: 'Station Square, Riverside.',
    memorable: 'The span rising for a barge.' },
  { id: 'corliss-lift-bridge', name: 'Corliss Lift Bridge', island: 'corliss', at: [42.6, 63.6], tier: 'secondary', kind: 'lift-bridge', h: 70,
    desc: 'A 5.6 km rail trestle with a vertical lift span over the ship channel.',
    why: 'The freight railroad has to cross the ship channel to reach the port.',
    look: 'Two lift towers in the middle of the water.',
    near: 'Tennalee Junction, Corliss Yard.',
    memorable: 'Freight trains waiting for ships.' },
  { id: 'harbor-bridge', name: 'Harbor Bridge', island: 'corliss', at: [42.5, 59.5], tier: 'secondary', kind: 'bridge', h: 25,
    desc: 'A steel girder bridge with a bascule span carrying I-121 across the Inner Harbor.',
    why: 'The port spur from the city.',
    look: 'Steel bascule leaves raised for tugs.',
    near: 'Harborside, Corliss Town.',
    memorable: 'Traffic stopping for the drawspan.' },
  { id: 'cape-fallon-light', name: 'Cape Fallon Light', island: 'graystone', at: [77.5, 89.4], tier: 'secondary', kind: 'lighthouse', h: 20,
    desc: 'A short white tower on the cliff-top at the north arm of Fallon Cove.',
    why: 'The cliffs already give height; a short tower is enough.',
    look: 'A white tower on dark cliffs.',
    near: 'Fallon, Fallon Harbor.',
    memorable: 'Its light at the top of a cliff.' },
  { id: 'cape-serena-light', name: 'Cape Serena Light', island: 'mirabel', at: [2.4, 24.4], tier: 'secondary', kind: 'lighthouse', h: 30,
    desc: 'A black-and-white banded iron lighthouse on the tip of the foreland.',
    why: 'Marks the cape and Serena Pass.',
    look: 'Banded tower over the beach ridges.',
    near: 'Cape Serena Beach, Long Swale Lake.',
    memorable: 'The light over the dune lakes.' },
  { id: 'mirabel-pier', name: 'Mirabel Pier', island: 'mirabel', at: [3.4, 47.0], inWater: true, tier: 'secondary', kind: 'pier', h: 6,
    desc: 'A 450 m concrete fishing pier with a T-head and a bait shop.',
    why: 'Built to reach past the surf zone.',
    look: 'Pilings marching into green water.',
    near: 'Pier District, Pier Beach.',
    memorable: 'Lights reflecting in the sea at night.' },
  { id: 'haversham-steeples', name: 'Haversham Steeples', island: 'saint-ambrose', at: [53.8, 47.4], tier: 'secondary', kind: 'steeples', h: 45,
    desc: 'Three white church steeples rising above the oaks of Haversham.',
    why: 'The town on the highest bluff.',
    look: 'Three white spires above the marsh.',
    near: 'Uptown Haversham, Bay Street.',
    memorable: 'The first sight of the town from the marsh.' },
  { id: 'ambrose-inlet-bridge', name: 'Ambrose Inlet Bridge', island: 'saint-ambrose', at: [70.6, 29.1], tier: 'secondary', kind: 'bridge', h: 22,
    desc: 'A high-rise concrete bridge over the inlet between Saint Ambrose and the Banks.',
    why: 'Inlet must stay open for boats.',
    look: 'A concrete arc over shoals.',
    near: 'Inlet Point, South Ambrose Beach.',
    memorable: 'The gateway to the Banks.' },
  { id: 'sabal-bridges', name: 'Sabal Bridges', island: 'sabal', at: [44.1, 3.8], tier: 'secondary', kind: 'bridge', h: 6,
    desc: 'A chain of low concrete trestles hopping across the flats to Sabal Key.',
    why: 'Shallow flats allow low bridges.',
    look: 'Low bridges over clear water.',
    near: 'Sabal Landing, Sabal Key.',
    memorable: 'Water colour changing under the bridges.' },
  { id: 'ossahatchee-skyway', name: 'Ossahatchee Skyway', island: 'ossahatchee', at: [41.0, 17.6], tier: 'secondary', kind: 'viaduct', h: 8,
    desc: 'A four-kilometre viaduct carrying the Trail over the swamp, built to let water flow under the road.',
    why: 'The old causeway blocked the swamp\'s slow flow.',
    look: 'A concrete ribbon through treetops.',
    near: 'Big Water, Big Water Tower.',
    memorable: 'Driving through the canopy.' },
  { id: 'big-water-tower', name: 'Big Water Tower', island: 'ossahatchee', at: [41.4, 16.4], tier: 'secondary', kind: 'tower', h: 15,
    desc: 'A wooden observation tower over the open water of Big Water.',
    why: 'The best view over the swamp.',
    look: 'A wooden tower over cypress.',
    near: 'Big Water, the Trail.',
    memorable: 'Alligators below.' },
  { id: 'highpine-fire-tower', name: 'Highpine Fire Tower', island: 'ossahatchee', at: [60.0, 14.0], tier: 'secondary', kind: 'tower', h: 30,
    desc: 'A steel fire tower on Long Ridge.',
    why: 'Fire watch over the swamp.',
    look: 'Steel tower above longleaf.',
    near: 'Highpine Knoll, Long Ridge.',
    memorable: 'The swamp to the horizon.' },
  { id: 'scrub-hill-tower', name: 'Scrub Hill Fire Tower', island: 'wickham', at: [13.5, 14.0], tier: 'secondary', kind: 'tower', h: 30,
    desc: 'A steel fire tower on Wickham\'s highest point.',
    why: 'Fire watch over the longleaf.',
    look: 'Tower over white sand.',
    near: 'Scrub Hill, Punchbowl Sink.',
    memorable: 'Both coasts in view.' },
  { id: 'gooseberry-fire-tower', name: 'Gooseberry Fire Tower', island: 'halcomb', at: [17.0, 75.0], tier: 'secondary', kind: 'tower', h: 18,
    desc: 'A fire lookout cab on Gooseberry Bald.',
    why: 'Watches the valley and the plateau.',
    look: 'Glass cab on steel legs.',
    near: 'Gooseberry Bald, Parkway.',
    memorable: 'Sunset over the Tableland.' },
  { id: 'cutstone-quarry-pit', name: 'Cutstone Quarry', island: 'graystone', at: [59.6, 70.3], inWater: true, tier: 'secondary', kind: 'quarry', h: 0,
    desc: 'Terraced granite benches cut into Cutstone Mountain, with a flooded lower pit and old derricks.',
    why: 'Fine granite close to the harbour.',
    look: 'Grey stepped benches.',
    near: 'Cutstone, Cutstone Quarry Hole.',
    memorable: 'Derrick masts on the rim.' },
  { id: 'coldwater-quarry', name: 'Coldwater Limestone Quarry', island: 'halcomb', at: [14.6, 84.0], inWater: true, tier: 'secondary', kind: 'quarry', h: 0,
    desc: 'A large working limestone quarry with crushers and conveyors on the valley\'s east side.',
    why: 'Limestone of the valley floor near the interstate and railroad.',
    look: 'Pale benches and dust plumes.',
    near: 'Coldwater Quarry Lake, I-21.',
    memorable: 'Blasting horns echoing across the valley.' },
  { id: 'landfill-hill', name: 'Corliss Landfill Hill', island: 'corliss', at: [51.5, 57.3], tier: 'secondary', kind: 'mound', h: 0,
    desc: 'A capped landfill mound 48 m high, grassed over with gas vents.',
    why: 'The city\'s waste on the industrial island.',
    look: 'A smooth green hill on flat land.',
    near: 'Cooling Pond, Corliss Stacks.',
    memorable: 'The highest point on Corliss is made of rubbish.' },
  { id: 'goliath-crane', name: 'Shipyard Goliath Crane', island: 'corliss', at: [55.6, 59.4], tier: 'secondary', kind: 'crane', h: 90,
    desc: 'A huge gantry crane straddling the main drydock.',
    why: 'Lifts ship modules into the drydock.',
    look: 'A giant red rectangle.',
    near: 'Shipyard, Spoil Island Beach.',
    memorable: 'The biggest machine in the islands.' },
  { id: 'refinery-flare', name: 'Refinery Flare', island: 'corliss', at: [45.0, 60.2], tier: 'secondary', kind: 'flare', h: 70,
    desc: 'A tall flare stack burning off excess gas.',
    why: 'Safety system of the refinery.',
    look: 'An orange flame on a stick.',
    near: 'Refinery Row.',
    memorable: 'The flame glowing on low clouds.' },
  { id: 'bellamy-elevator', name: 'Bellamy Grain Elevator', island: 'bellamy', at: [19.2, 37.8], tier: 'secondary', kind: 'elevator', h: 45,
    desc: 'Concrete grain silos beside the railroad.',
    why: 'Collects grain and peanuts for shipping by rail.',
    look: 'Grey silos above flat land.',
    near: 'Depot District, Bellamy & Southern.',
    memorable: 'The tallest thing in town.' },
  { id: 'peanut-water-tower', name: 'Peanut Water Tower', island: 'bellamy', at: [18.4, 38.9], tier: 'secondary', kind: 'water-tower', h: 40,
    desc: 'A water tower painted to look like a giant peanut.',
    why: 'Town water tower in the peanut-growing county.',
    look: 'A tan peanut on legs.',
    near: 'Courthouse Square.',
    memorable: 'Everyone photographs it.' },
  { id: 'calder-stadium', name: 'Calder Stadium', island: 'calder', at: [39.4, 57.4], tier: 'secondary', kind: 'stadium', h: 50,
    desc: 'The football stadium on reclaimed land by the harbour.',
    why: 'Large flat site near the highway.',
    look: 'A bowl of lights.',
    near: 'Stadium District, Mill Creek.',
    memorable: 'Light glowing over the harbour.' },
  { id: 'ledford-tower', name: 'Ledford Observation Tower and Tramway', island: 'halcomb', at: [27.0, 69.0], tier: 'secondary', kind: 'tower', h: 120,
    desc: 'A needle-like observation tower and an aerial tramway running up the side of Cove Mountain.',
    why: 'Tourist town at the foot of the mountains.',
    look: 'A needle and swinging cars.',
    near: 'Ledford Strip, Gap Road.',
    memorable: 'Tram cars against the mountain.' },
  { id: 'calder-harbor-light', name: 'Calder Harbor Light', island: 'calder', at: [41.6, 61.3], tier: 'secondary', kind: 'lighthouse', h: 18,
    desc: 'A red cast-iron light at the tip of Calder Point.',
    why: 'Marks the harbour entrance.',
    look: 'A red tower on the seawall.',
    near: 'Calder Point.',
    memorable: 'Red against grey water.' },
  { id: 'graystone-head-light', name: 'Graystone Head Light', island: 'graystone', at: [74.6, 69.6], tier: 'secondary', kind: 'lighthouse', h: 15,
    desc: 'A stubby white tower on the headland at the sound mouth.',
    why: 'Marks the turn into Cassena Sound.',
    look: 'White tower on dark rock.',
    near: 'Graystone Head, Head Cove Beach.',
    memorable: 'Ships passing close by.' },
  { id: 'cayo-lejos-light', name: 'Cayo Lejos Light', island: 'sabal', at: [48.0, -2.8], tier: 'secondary', kind: 'lighthouse', h: 25,
    desc: 'A skeletal iron screwpile light on the outermost key.',
    why: 'Marks the edge of the flats.',
    look: 'An iron skeleton on a sandbar.',
    near: 'Cayo Lejos.',
    memorable: 'The last structure before open water.' },
  { id: 'bellamy-solar', name: 'Bellamy Solar Farm', island: 'bellamy', at: [21.6, 44.2], tier: 'secondary', kind: 'solar', h: 3,
    desc: 'Rows of solar panels covering an old cotton field.',
    why: 'Flat, cleared farmland near transmission lines.',
    look: 'Dark blue rectangles.',
    near: 'WCDR Mast, Lake Ocosta.',
    memorable: 'Panels flashing in the sun from the air.' },
  { id: 'lake-whitlock-dam', name: 'Lake Whitlock Dam', island: 'graystone', at: [58.15, 83.35], inWater: true, tier: 'secondary', kind: 'dam', h: 12,
    desc: 'A low stone dam with a waterfall spillway at the outlet of Lake Whitlock.',
    why: 'Built to create the lake.',
    look: 'Water sheeting over stone.',
    near: 'Whitlock, Highlands Road.',
    memorable: 'The spillway falls under the road bridge.' },
  { id: 'bright-water-gullies', name: 'Bright Water Gullies', island: 'graystone', at: [68.6, 70.8], tier: 'secondary', kind: 'canyon', h: 0,
    desc: 'A maze of steep red, orange and white gullies up to 40 m deep, cut into the soft weathered rock of an abandoned field.',
    why: 'Deeply weathered saprolite, once exposed, erodes very quickly.',
    look: 'Bands of red, pink and cream in steep walls.',
    near: 'Bright Water Road, Graystone Piedmont Pines.',
    memorable: 'A painted canyon in the middle of farmland.' },
  { id: 'hollow-reach-span', name: 'Hollow Reach Power Span', island: 'halcomb', at: [46.8, 68.4], tier: 'secondary', kind: 'pylons', h: 110,
    desc: 'A transmission line strung across the mouth of Hollow Reach between towers on either headland.',
    why: 'Power to Graystone.',
    look: 'Wires across the gorge mouth.',
    near: 'Dogwood Point, Lookoff Mountain.',
    memorable: 'Orange marker balls on the wires.' },

  // ================================================================= LOCAL
  { id: 'blind-tunnel', name: 'Blind Tunnel', island: 'graystone', at: [64.6, 78.2], tier: 'local', kind: 'tunnel-portal', h: 0,
    desc: 'A stone-lined railroad tunnel portal at the foot of the Blue Wall that goes 400 m into the mountain and stops at a rock face.',
    why: 'Graded and bored for a railroad up the escarpment that was never completed.',
    look: 'A dark arch in a fern-covered cliff.',
    near: 'Blue Wall Incline, Anvil Rock.',
    memorable: 'Cold air flowing out of the dark.' },
  { id: 'bearpen-tunnel', name: 'Bearpen Tunnel', island: 'halcomb', at: [45.6, 75.3], tier: 'local', kind: 'tunnel-portal', h: 0,
    desc: 'A two-lane highway tunnel that carries the Gate Road under the spur of Bearpen Knob straight onto the Gate Bridge.',
    why: 'The spur stands between the Hollow Reach rim and the bridge shelf.',
    look: 'Portal lights and the bridge visible through the tunnel.',
    near: 'Gate Bridge, Gate Shelf.',
    memorable: 'Daylight and bridge at the end of the tunnel.' },
  { id: 'shay-locomotive', name: 'Big Laurel Shay', island: 'halcomb', at: [36.6, 84.6], tier: 'local', kind: 'wreck', h: 4,
    desc: 'The rusted frame and boiler of a geared logging locomotive lying on its side at the end of the old grade.',
    why: 'Left where it stood when the logging railroad was pulled up.',
    look: 'Orange rust and moss.',
    near: 'Big Laurel Logging Grade.',
    memorable: 'A locomotive in the middle of a forest.' },
  { id: 'sill-canal', name: 'The Sill Canal', island: 'ossahatchee', at: [50.0, 12.0], tier: 'local', kind: 'canal', h: 0,
    desc: 'A dead-straight canal dug eight kilometres into the swamp from Long Ridge, with a spoil bank along one side.',
    why: 'Dug to drain the swamp; the swamp is perched and the canal never drained it.',
    look: 'A ruler-straight line of water.',
    near: 'Sill Lake, Sill Bay Forest.',
    memorable: 'Unnaturally straight in a world of curves.' },
  { id: 'cypress-tram', name: 'Cypress Tram Grade', island: 'ossahatchee', at: [51.0, 14.8], tier: 'local', kind: 'grade', h: 0,
    desc: 'A raised logging railroad grade running into the swamp, rails gone, with rotting crossties.',
    why: 'Built to haul cypress logs out of the swamp.',
    look: 'A straight raised path through cypress.',
    near: 'Tolar, Sill Canal.',
    memorable: 'Crossties sticking out of the mud.' },
  { id: 'turpentine-still', name: 'Turpentine Still Ruins', island: 'wickham', at: [11.0, 11.0], tier: 'local', kind: 'ruins', h: 3,
    desc: 'Brick firebox, copper fragments and rusted barrel hoops of a turpentine distillery.',
    why: 'The longleaf forests were tapped for resin.',
    look: 'Brick ruins among pines.',
    near: 'Turpentine Tram, Blue Sink.',
    memorable: 'Pines nearby still carry their catface scars.' },
  { id: 'phosphate-dragline', name: 'Phosphate Dragline', island: 'wickham', at: [17.4, 7.6], tier: 'local', kind: 'wreck', h: 30,
    desc: 'An abandoned walking dragline with its boom collapsed over a flooded pit.',
    why: 'Left behind when phosphate mining stopped.',
    look: 'A rusted machine the size of a house.',
    near: 'Phosphate Pits, Sand Lake.',
    memorable: 'A giant machine in the wilderness.' },
  { id: 'wickham-spring', name: 'Wickham Spring', island: 'wickham', at: [5.5, 12.0], tier: 'local', kind: 'spring', h: 0,
    desc: 'A large spring where water boils up from a limestone vent into a pool of electric blue.',
    why: 'The aquifer beneath the sand ridge discharges near the coast.',
    look: 'Blue water over white sand.',
    near: 'Wickham Spring Run, Springs Hammock.',
    memorable: 'Water 22 °C all year round.' },
  { id: 'seacow-spring', name: 'Seacow Spring', island: 'wickham', at: [6.0, 17.0], tier: 'local', kind: 'spring', h: 0,
    desc: 'A spring where manatees gather in winter.',
    why: 'Warm spring water in cold months.',
    look: 'Grey shapes in clear water.',
    near: 'Wickham, Seacow Bar.',
    memorable: 'Manatees in winter.' },
  { id: 'shell-ring', name: 'Kettle Shell Ring', island: 'saint-ambrose', at: [47.0, 31.2], tier: 'local', kind: 'mound', h: 4,
    desc: 'A ring-shaped ridge of oyster shell 80 m across and four metres high, overgrown with cedar and palm.',
    why: 'A shell midden on the edge of the marsh.',
    look: 'A wooded ring in the marsh.',
    near: 'Kettle, Kettle Island Pines.',
    memorable: 'A perfect ring seen from the air.' },
  { id: 'tabby-ruins', name: 'Kettle Tabby Ruins', island: 'saint-ambrose', at: [50.6, 33.4], tier: 'local', kind: 'ruins', h: 6,
    desc: 'Roofless walls of tabby — oyster-shell concrete — standing in the woods.',
    why: 'Buildings made from the local shell and lime.',
    look: 'Grey shell-studded walls.',
    near: 'Kettle, Coastal Highway.',
    memorable: 'Walls studded with shells.' },
  { id: 'rice-trunks', name: 'Rice Hope Trunk Gates', island: 'saint-ambrose', at: [47.4, 41.2], tier: 'local', kind: 'structure', h: 2,
    desc: 'Wooden sluice gates in the dikes of old rice fields, still controlling the water.',
    why: 'Rice was grown in diked fields flooded with fresh tidal water.',
    look: 'Wooden boxes in earthen dikes.',
    near: 'Rice Reserve, Rice Hope.',
    memorable: 'Old dikes still holding water.' },
  { id: 'beach-line-trestle', name: 'Beach Line Trestle Pilings', island: 'saint-ambrose', at: [57.0, 45.0], inWater: true, tier: 'local', kind: 'ruins', h: 3,
    desc: 'A line of timber pilings crossing the marsh where an excursion railroad once ran to the beach.',
    why: 'Built to carry visitors to the ocean beach before the road.',
    look: 'Black pilings marching across the marsh.',
    near: 'Haversham River, Banks Highway.',
    memorable: 'Pilings in a straight line to nowhere.' },
  { id: 'boneyard-trees', name: 'Boneyard Beach Trees', island: 'saint-ambrose', at: [69.6, 34.4], tier: 'local', kind: 'natural', h: 10,
    desc: 'Bleached dead oaks and pines standing on an eroding beach.',
    why: 'The shoreline is retreating into the forest.',
    look: 'Silver trees in the surf.',
    near: 'Boneyard Beach.',
    memorable: 'Sunrise through dead trees.' },
  { id: 'surf-houses', name: 'Houses in the Surf', island: 'saint-ambrose', at: [68.8, 44.2], tier: 'local', kind: 'ruins', h: 8,
    desc: 'A row of beach houses standing on pilings in the surf zone after the beach eroded out from under them.',
    why: 'Shoreline retreat on the barrier.',
    look: 'Houses with waves breaking beneath.',
    near: 'Ambrose Beach.',
    memorable: 'Waves washing under living rooms.' },
  { id: 'drowned-church', name: 'Drowned Church Steeple', island: 'halcomb', at: [36.2, 73.0], inWater: true, tier: 'local', kind: 'ruins', h: 12,
    desc: 'The stone steeple of a church on the old cove floor, which rises above the water only when the lake is drawn down in autumn.',
    why: 'The cove was flooded by Calloway Lake.',
    look: 'A steeple standing in mud flats.',
    near: 'Calloway Lake, Calloway village.',
    memorable: 'Only visible a few weeks a year.' },
  { id: 'gap-inn-foundations', name: 'Ledford Gap Foundations', island: 'halcomb', at: [27.5, 79.85], tier: 'local', kind: 'ruins', h: 1,
    desc: 'Stone foundations and a chimney base of a demolished hotel at the gap.',
    why: 'A hotel stood at the pass when the road was built.',
    look: 'Stone outlines in the grass.',
    near: 'Ledford Gap Overlook, Parkway.',
    memorable: 'Steps leading up to nothing.' },
  { id: 'narrows-ferry-slip', name: 'Old Narrows Ferry Slip', island: 'halcomb', at: [11.0, 89.4], tier: 'local', kind: 'ruins', h: 3,
    desc: 'A concrete ferry ramp and rotting dolphins at the old crossing, below the bridge.',
    why: 'The ferry crossed here before the bridge.',
    look: 'A ramp sliding into the water.',
    near: 'Narrows Landing, Narrows Bridge.',
    memorable: 'Fishermen use it as a launch.' },
  { id: 'coldwater-covered-bridge', name: 'Coldwater Covered Bridge', island: 'halcomb', at: [11.6, 76.6], tier: 'local', kind: 'bridge', h: 6,
    desc: 'A red wooden covered bridge on an old road across the Coldwater River.',
    why: 'Built where the old valley road crossed the river.',
    look: 'A red barn-like bridge over clear water.',
    near: 'Coldwater, Old Valley Road.',
    memorable: 'The only covered bridge in the islands.' },
  { id: 'old-hominy-bridge', name: 'Old Hominy Bridge', island: 'halcomb', at: [22.4, 68.4], tier: 'local', kind: 'ruins', h: 8,
    desc: 'A collapsed steel truss bridge lying in Hominy Creek beside the concrete bridge that replaced it.',
    why: 'Washed out in a flood and left in place.',
    look: 'Twisted steel in the creek.',
    near: 'Hominy, Hominy Road.',
    memorable: 'Old and new bridges side by side.' },
  { id: 'serena-waterslides', name: 'Serena Waterslide Ruins', island: 'mirabel', at: [3.6, 30.8], tier: 'local', kind: 'ruins', h: 15,
    desc: 'Cracked concrete pools and the faded fibreglass tubes of an abandoned water park, overgrown with vines.',
    why: 'A resort attraction built on the foreland and abandoned.',
    look: 'Bright fibreglass tubes under kudzu.',
    near: 'Port Serena, Beach Road.',
    memorable: 'Faded colours in the jungle.' },
  { id: 'ghost-subdivision', name: 'Ocosta Shores', island: 'bellamy', at: [27.6, 36.0], tier: 'local', kind: 'ruins', h: 0,
    desc: 'A grid of paved streets, street signs and fire hydrants with no houses, slowly being reclaimed by pines.',
    why: 'A subdivision laid out and never built.',
    look: 'Streets with nothing on them.',
    near: 'Brown\'s Bay, Bellamy Highway.',
    memorable: 'Street signs in a pine forest.' },
  { id: 'drive-in-screen', name: 'Bellamy Drive-In Screen', island: 'bellamy', at: [24.0, 41.2], tier: 'local', kind: 'ruins', h: 18,
    desc: 'The tall screen tower of an abandoned drive-in theatre beside SR 9.',
    why: 'Roadside business on the highway.',
    look: 'A blank screen above a weedy field.',
    near: 'Bellamy Highway, Kinard.',
    memorable: 'A blank white screen at dusk.' },
  { id: 'merrin-shoals-wreck', name: 'Merrin Shoals Boiler', island: 'gannet', at: [85.6, 7.4], tier: 'local', kind: 'wreck', h: 3,
    desc: 'The rusted boiler and ribs of a steamship exposed on the shoals at low tide.',
    why: 'The shoals have trapped many ships.',
    look: 'A rusty cylinder in the breakers.',
    near: 'Cape Merrin Point, Lighthouse Beach.',
    memorable: 'Breakers bursting over the boiler.' },
  { id: 'sunken-dredge', name: 'Sunken Dredge', island: 'corliss', at: [56.9, 56.6], tier: 'local', kind: 'wreck', h: 6,
    desc: 'The hulk of a dredge resting on a sandbar off Corliss, its superstructure above water.',
    why: 'Sank while working the ship channel.',
    look: 'A rusty hulk with birds on it.',
    near: 'Spoil Island Beach, Shipyard.',
    memorable: 'Cormorants drying their wings on the wreck.' },
  { id: 'kestrel-lookout', name: 'Kestrel Concrete Tower', island: 'gannet', at: [72.4, 26.4], tier: 'local', kind: 'tower', h: 18,
    desc: 'A windowless concrete observation tower standing alone in the dunes.',
    why: 'Built on the dunes for its view of the sea.',
    look: 'A grey cylinder with narrow slits.',
    near: 'Kestrel, Kestrel Thickets.',
    memorable: 'A strange tower in the dunes.' },
  { id: 'fish-camp', name: 'Little Black Fish Camp', island: 'ossahatchee', at: [26.4, 15.2], tier: 'local', kind: 'buildings', h: 5,
    desc: 'Stilt cabins, a bait shop and a boat ramp on the Little Black River.',
    why: 'Access to the river for fishing.',
    look: 'Cabins on stilts over black water.',
    near: 'Little Black River, Sawpit Pass Bridge.',
    memorable: 'Cane poles and screened porches.' },
  { id: 'airboat-landing', name: 'Trail Airboat Landing', island: 'ossahatchee', at: [45.0, 17.8], tier: 'local', kind: 'buildings', h: 4,
    desc: 'An airboat ride landing beside the Trail with a gift shop.',
    why: 'Access to the open prairies.',
    look: 'Airboats with giant fans.',
    near: 'The Trail, Ossahatchee Skyway.',
    memorable: 'The roar of airboat engines.' },
  { id: 'calloway-houseboats', name: 'Calloway Houseboats', island: 'halcomb', at: [36.6, 72.2], inWater: true, tier: 'local', kind: 'boats', h: 4,
    desc: 'Floating houses moored in rows in a cove of Calloway Lake.',
    why: 'Sheltered cove near the marina.',
    look: 'Floating houses on green water.',
    near: 'Calloway Marina, Calloway village.',
    memorable: 'A floating neighbourhood.' },
  { id: 'tobacco-barns', name: 'Coldwater Tobacco Barns', island: 'halcomb', at: [12.6, 74.0], tier: 'local', kind: 'barns', h: 9,
    desc: 'Tall, narrow log barns with gaps between the boards for air-curing tobacco.',
    why: 'Tobacco grown on the valley bottomland.',
    look: 'Dark barns in pasture.',
    near: 'Old Valley Road, Coldwater.',
    memorable: 'Light shining through the gaps.' },

  // ================================================================== MICRO
  { id: 'rich-chimney', name: 'Rich Mountain Chimney', island: 'halcomb', at: [18.4, 81.4], tier: 'micro', kind: 'ruins', h: 7,
    desc: 'A lone fieldstone chimney in a meadow where a house once stood.',
    why: 'An old homestead clearing.',
    look: 'A chimney in a meadow.',
    near: 'Rich Mountain.',
    memorable: 'Daffodils still bloom around it.' },
  { id: 'car-hollow', name: 'Rich Creek Car Bank', island: 'halcomb', at: [21.2, 85.0], tier: 'micro', kind: 'wreck', h: 2,
    desc: 'A line of old car bodies laid along a creek bank to stop erosion.',
    why: 'Used as riprap along the creek.',
    look: 'Rusted car bodies in the creek bank.',
    near: 'Rich Creek, Narrows Road.',
    memorable: 'Old fenders in the water.' },
  { id: 'sugar-shack', name: 'Sugartree Sugar Shack', island: 'halcomb', at: [20.6, 72.6], tier: 'micro', kind: 'ruins', h: 3,
    desc: 'Stone foundations and rusted kettles of a maple sugar shack.',
    why: 'Maples in the north-facing hollows.',
    look: 'Kettles in the leaves.',
    near: 'Sugartree Knob.',
    memorable: 'Kettles full of leaves.' },
  { id: 'gooseberry-boardwalk', name: 'Gooseberry Boardwalk', island: 'halcomb', at: [17.7, 74.1], inWater: true, tier: 'micro', kind: 'path', h: 0,
    desc: 'A plank walkway across the bog pond.',
    why: 'Protects the bog.',
    look: 'Boards over moss.',
    near: 'Gooseberry Pond.',
    memorable: 'Sundews beside the boards.' },
  { id: 'hickory-rock-shelter', name: 'Hickory Falls Rock Shelter', island: 'halcomb', at: [8.75, 80.8], tier: 'micro', kind: 'cave', h: 0,
    desc: 'An overhang behind the falls where the soft rock has eroded under the caprock.',
    why: 'Soft shale beneath hard sandstone.',
    look: 'A curtain of water across the entrance.',
    near: 'Hickory Falls.',
    memorable: 'Standing behind a waterfall.' },
  { id: 'blue-hole-rope', name: 'Blue Hole Rope Swing', island: 'halcomb', at: [10.05, 82.85], inWater: true, tier: 'micro', kind: 'tree', h: 15,
    desc: 'A rope swing on a sycamore over the Blue Hole.',
    why: 'The deep spring pool.',
    look: 'Rope over blue water.',
    near: 'Blue Hole.',
    memorable: 'Jumping into icy blue water.' },
  { id: 'stillhouse-ruins', name: 'Stillhouse Branch Ruins', island: 'graystone', at: [56.6, 89.6], tier: 'micro', kind: 'ruins', h: 2,
    desc: 'A rock-walled pit, copper scraps and barrel staves beside a hidden spring.',
    why: 'A clean spring in a secluded hollow.',
    look: 'Stone wall half buried in leaves.',
    near: 'Stillhouse Road.',
    memorable: 'Copper turned green.' },
  { id: 'kudzu-house', name: 'Kudzu House', island: 'graystone', at: [68.2, 71.2], tier: 'micro', kind: 'ruins', h: 8,
    desc: 'An abandoned farmhouse completely engulfed in kudzu vines.',
    why: 'Abandoned fields on the Piedmont.',
    look: 'A green shape of a house.',
    near: 'Bright Water Gullies.',
    memorable: 'Vines covering every surface.' },
  { id: 'weathering-pits', name: 'Bald Rock Pools', island: 'graystone', at: [61.0, 83.4], tier: 'micro', kind: 'natural', h: 0,
    desc: 'Round pools worn into the granite that fill with rainwater and tiny plants.',
    why: 'Water dissolves the granite in small hollows.',
    look: 'Pools reflecting the sky.',
    near: 'Bald Rock.',
    memorable: 'Little mirrors on bare rock.' },
  { id: 'fallon-net-lofts', name: 'Fallon Net Lofts', island: 'graystone', at: [76.9, 88.0], tier: 'micro', kind: 'buildings', h: 6,
    desc: 'Tall narrow wooden lofts for drying nets on the quay.',
    why: 'The fishing harbour.',
    look: 'Black-tarred wooden buildings.',
    near: 'Fallon Harbor.',
    memorable: 'The smell of tar and salt.' },
  { id: 'catface-pine', name: 'Catface Pine', island: 'wickham', at: [13.0, 12.6], tier: 'micro', kind: 'tree', h: 30,
    desc: 'An old longleaf pine with a deep V-shaped scar from resin tapping.',
    why: 'Pines tapped for turpentine.',
    look: 'A face-like scar on the trunk.',
    near: 'Turpentine Still Ruins.',
    memorable: 'Old metal cups still nailed to it.' },
  { id: 'bottle-tree', name: 'Rice Hope Bottle Tree', island: 'saint-ambrose', at: [45.7, 40.9], tier: 'micro', kind: 'tree', h: 6,
    desc: 'A cedar tree with blue glass bottles on its branches beside a farmhouse.',
    why: 'Yard decoration in the hamlet.',
    look: 'Blue glass glinting in the sun.',
    near: 'Rice Hope.',
    memorable: 'The bottles hum in the wind.' },
  { id: 'hollow-cypress', name: 'Hollow Cypress', island: 'ossahatchee', at: [39.8, 15.0], inWater: true, tier: 'micro', kind: 'tree', h: 35,
    desc: 'An ancient cypress with a hollow trunk you can paddle a canoe into.',
    why: 'Too hollow for the loggers to bother with.',
    look: 'A doorway in a giant tree.',
    near: 'Big Water.',
    memorable: 'Paddling inside a tree.' },
  { id: 'mangrove-skeletons', name: 'Freeze-Killed Mangroves', island: 'ossahatchee', at: [50.0, 5.4], tier: 'micro', kind: 'natural', h: 3,
    desc: 'Grey skeletons of black mangroves killed by a hard freeze, with green regrowth among them.',
    why: 'The northern limit of mangroves.',
    look: 'Grey and green tangles.',
    near: 'Sabal Coast Mangroves.',
    memorable: 'Life and death side by side.' },
  { id: 'old-lifesaving-slab', name: 'Lifesaving Station Slab', island: 'mirabel', at: [0.9, 30.2], tier: 'micro', kind: 'ruins', h: 1,
    desc: 'A concrete slab and rebar in the dunes.',
    why: 'A station once stood on the open foreland.',
    look: 'Concrete in the sand.',
    near: 'Old Station Beach.',
    memorable: 'Rebar poking out of dunes.' },
  { id: 'sheepshead-bait-shack', name: 'Sheepshead Bait Shack', island: 'gannet', at: [77.2, 16.6], tier: 'micro', kind: 'buildings', h: 4,
    desc: 'A weathered bait and tackle shack beside the inlet bridge.',
    why: 'Inlet fishing.',
    look: 'Hand-painted signs.',
    near: 'Shellbank Beach.',
    memorable: 'The hand-painted fish menu.' },
  { id: 'mile-zero', name: 'SR 1 Mile Zero', island: 'sabal', at: [52.6, 0.6], tier: 'micro', kind: 'sign', h: 2,
    desc: 'The zero-mile marker at the end of the Keys Highway.',
    why: 'The southern end of the road.',
    look: 'A green sign beside the water.',
    near: 'Cayo Viento.',
    memorable: 'The end of the road.' },
  { id: 'iron-cove-seeps', name: 'Iron Cove Seeps', island: 'bellamy', at: [13.8, 50.6], tier: 'micro', kind: 'natural', h: 0,
    desc: 'Orange iron-rich seeps staining the bluff and beach.',
    why: 'Groundwater leaching iron from the Red Hills.',
    look: 'Orange stains on red clay.',
    near: 'Iron Cove Beach.',
    memorable: 'Rust-coloured water.' },
  { id: 'sugarloaf-cemetery', name: 'Sugarloaf Cemetery', island: 'bellamy', at: [17.4, 49.6], tier: 'micro', kind: 'cemetery', h: 1,
    desc: 'An old hilltop cemetery under cedars beside the church.',
    why: 'High ground for burial.',
    look: 'Old headstones under cedars.',
    near: 'Sugarloaf Hill.',
    memorable: 'Views over the farmland.' },
  { id: 'corliss-mill-whistle', name: 'Paper Mill Whistle', island: 'corliss', at: [49.6, 57.0], tier: 'micro', kind: 'sound', h: 30,
    desc: 'The steam whistle on the paper mill heard across the island at shift change.',
    why: 'Mill shift signal.',
    look: 'A brass whistle on a pipe.',
    near: 'Paper Mill, Corliss Town.',
    memorable: 'The whistle at 7 a.m.' },
  { id: 'gasholder-ring', name: 'Gasholder Ring', island: 'calder', at: [32.7, 60.7], tier: 'micro', kind: 'structure', h: 35,
    desc: 'The iron frame of a Victorian gasholder now enclosing a park.',
    why: 'The old gasworks.',
    look: 'An iron ring of columns.',
    near: 'Gasworks district.',
    memorable: 'Lit at night.' },
  { id: 'mill-creek-outfall', name: 'Mill Creek Outfall', island: 'calder', at: [41.4, 58.2], inWater: true, tier: 'micro', kind: 'structure', h: 4,
    desc: 'A stone arch where the buried Mill Creek emerges into the harbour.',
    why: 'The creek was culverted under the city.',
    look: 'A dark stone arch at the waterline.',
    near: 'Mill Creek, Harborside.',
    memorable: 'A hidden creek reaching the sea.' },
  { id: 'cedar-light', name: 'Cedar Point Light', island: 'wickham', at: [10.0, 0.2], tier: 'micro', kind: 'lighthouse', h: 12,
    desc: 'A small iron skeleton light on the oyster bars off Cedar Point.',
    why: 'Marks the channel to Cedar Shoals.',
    look: 'An iron frame on the bars.',
    near: 'Cedar Shoals.',
    memorable: 'Pelicans perched on top.' },
  { id: 'heron-rookery', name: 'Pelican Key Rookery', island: 'sabal', at: [33.0, -1.8], tier: 'micro', kind: 'natural', h: 4,
    desc: 'A small mangrove key covered in nesting pelicans and herons.',
    why: 'Isolated key safe from predators.',
    look: 'White birds covering green mangroves.',
    near: 'Bonefish Key.',
    memorable: 'The noise of the colony.' },
];
