// Register: 50 mountains. Coordinates and elevations live in
// world/geography.mjs PEAKS (same ids); this file carries the descriptions.
// Fields: where, desc (physical description), why (geographic justification),
// look (visual identity), near (nearby environmental features), memorable.

export const MOUNTAINS = [
  // ---------------------------------------------------------------- Halcomb
  { id: 'ledford-dome', kind: 'dome summit',
    where: 'Centre of the Balsam Crest, 1.7 km east of Ledford Gap',
    desc: 'The highest point in the archipelago: a broad, rounded summit wrapped in dark red spruce and Fraser fir, crowned by a concrete observation tower reached by a spiral ramp. Grey trunks of dead fir stand among the living trees on the windward south-west shoulder.',
    why: 'The crest is the core of the old crystalline massif, where resistant gneiss has outlasted the surrounding schists; at 2,047 m it is high enough for a relict boreal forest even at 30° N.',
    look: 'Black-green cone of conifers above a paler band of hardwoods, often capped in cloud while the valleys are clear; the tower\'s white ramp is visible from Calder on clear winter mornings.',
    near: 'Ledford Gap, the Parkway, Ledford Dome Road parking lot, Coldspring Knob, the Pigeonroost and Ledford Prong headwaters.',
    memorable: 'From the tower the whole archipelago lies below — the North Face dropping to the Narrows, Calloway Lake, the city on its island, and the flat southern islands fading into haze.' },
  { id: 'mount-sawyer', kind: 'mountain',
    where: 'Balsam Crest, 3.5 km east of Ledford Dome',
    desc: 'A long, double-topped summit ridge under spruce–fir with grassy openings where old fir blowdowns never regrew. A rough trail follows the crest between its two tops.',
    why: 'Second culmination of the same resistant gneiss band that forms Ledford Dome; the crest is continuous here because no stream has cut back through it.',
    look: 'A level skyline of dark conifers seen from the south as a wall above Calloway Lake.',
    near: 'Mount Callahan spur, Hemlock Knob, Callahan Branch headwaters, the Parkway.',
    memorable: 'Its flat top makes the crest look like a rampart running east from Ledford Dome.' },
  { id: 'mount-callahan', kind: 'mountain',
    where: 'North Face, on the spur north of Mount Sawyer',
    desc: 'A massive, free-standing mountain that rises almost 2,000 m directly from the Narrows in less than five kilometres. Grey cliffs of slate and phyllite break out on its north-west face below a summit of spruce, fir and heath.',
    why: 'A thrust slice of harder metasediment pushed north over the softer rocks; the Narrows strait has cut away its base, leaving the steepest relief in the islands.',
    look: 'Seen from the mainland bridge it looks like a separate peak standing in front of the crest, with pale cliffs catching the late sun.',
    near: 'Callahan Branch, Big Laurel Creek, the Narrows Road, Pigeonroost.',
    memorable: 'The mountain fills the windshield the whole way across the Narrows Bridge.' },
  { id: 'coldspring-knob', kind: 'knob',
    where: 'Balsam Crest, west of Ledford Gap',
    desc: 'A sharp knob with a cluster of steel relay towers and their equipment huts on a cleared summit, surrounded by northern hardwoods and spruce.',
    why: 'Part of the main crest; its summit was cleared because it has the clearest radio path to both Calder and the mainland.',
    look: 'Red aircraft lights blink on its towers at night above Ledford.',
    near: 'Ledford Gap, Thunderstone spur, Brushy Mountain, the Parkway.',
    memorable: 'The towers are the first thing travellers see from the Gap Road switchbacks below.' },
  { id: 'hemlock-knob', kind: 'knob',
    where: 'Balsam Crest, between Mount Sawyer and The Steeples',
    desc: 'A rounded summit whose north slope holds a stand of dead and dying hemlocks — grey, needle-less trunks above a dense rhododendron understory.',
    why: 'Cool, north-facing slope where hemlock once dominated the coves below the spruce zone.',
    look: 'A pale grey patch on an otherwise dark green flank, visible from the North Face.',
    near: 'Big Laurel Creek headwaters, Huckleberry Knob, the Parkway.',
    memorable: 'The grey "ghost forest" on its shoulder is unlike any other slope on the island.' },
  { id: 'painted-bald', kind: 'grassy bald',
    where: 'Western Balsam Crest, above the Hominy headwaters',
    desc: 'A treeless summit meadow of oatgrass and blueberry ringed by stunted beech, ablaze with flame azalea in June and red blueberry leaves in October.',
    why: 'Exposed summit swept by winter winds and ice, where an open meadow has persisted for generations.',
    look: 'A tawny bald patch on the dark crest, unmistakable from Hominy Bay.',
    near: 'Sugartree Knob, Stormhead Mountain, the Parkway overlooks.',
    memorable: 'The only place on the crest where you can see in every direction while standing in grass.' },
  { id: 'stormhead', kind: 'mountain',
    where: 'Western Balsam Crest, where the Rich Mountain spur branches north',
    desc: 'A steep-sided peak with a craggy summit of mica schist, oak and rhododendron on its flanks, and windswept beech on top.',
    why: 'Junction of two ridges, so it stands slightly above both; storms off Serena Bay hit it first.',
    look: 'Usually the first peak to disappear into afternoon thunderheads.',
    near: 'Rich Mountain, Painted Bald, Gooseberry Bald, the Parkway.',
    memorable: 'Lightning-scarred snags on the summit and a reputation for the first storm of the day.' },
  { id: 'the-steeples', kind: 'rock pinnacles',
    where: 'Eastern Balsam Crest, above Big Laurel Top',
    desc: 'Twin spires of steeply tilted slate rising above heath and stunted pine, joined by a narrow rocky saddle. Loose plates of rock litter the trail to the top.',
    why: 'Near-vertical beds of slate weather into knife-edges where the crest narrows.',
    look: 'Two sharp points like needles on the skyline, visible from Riverside and the Tennalee River Bridge.',
    near: 'Hemlock Knob, Sawyer Gap, Big Laurel spur, the Parkway.',
    memorable: 'The only jagged summit on a crest of rounded domes.' },
  { id: 'blackstrap-knob', kind: 'knob',
    where: 'North Face, on the spur west of Mount Callahan',
    desc: 'A steep knob of dark slate with a scar of fresh rock where a landslide stripped its west face to bedrock.',
    why: 'Thin soils over steeply dipping slate fail during the heavy remnant-hurricane rains that hit the North Face.',
    look: 'A long pale streak down a dark green slope.',
    near: 'Pigeonroost Creek, the Gap Road switchbacks, Mount Callahan.',
    memorable: 'The landslide scar is visible from the Narrows Road and from boats in the strait.' },
  { id: 'thunderstone', kind: 'mountain',
    where: 'North Face, spur between Rich Creek and Pigeonroost Creek',
    desc: 'A broad, steep mountain with a summit of heath and table mountain pine and a north face of mossy boulder fields.',
    why: 'One of the parallel spurs that radiate north from the crest toward the Narrows.',
    look: 'A tall, dark pyramid above Narrows Landing.',
    near: 'Rich Creek, Pigeonroost Creek, the Narrows Road.',
    memorable: 'Its boulder field rings hollowly under foot and holds snow weeks after the summit melts.' },
  { id: 'gooseberry-bald', kind: 'grassy bald',
    where: 'Western end of the Balsam Crest above Shady Gap',
    desc: 'A grassy summit with a steel fire lookout tower, a small sphagnum pond, and the first Parkway pull-off after the climb from Shady Gap.',
    why: 'The crest drops away westward here, giving an unobstructed view over the Coldwater Valley and the Hickory Tableland.',
    look: 'Fire tower silhouetted on a bare summit.',
    near: 'Gooseberry Pond, Sheepback Bald, Pinnacle Knob, the Parkway.',
    memorable: 'Sunset from the tower sets the whole Tableland escarpment glowing orange.' },
  { id: 'big-laurel-top', kind: 'mountain',
    where: 'North Face spur above Big Laurel village',
    desc: 'A heavily forested summit cut by an abandoned logging railroad grade that zigzags up its western flank.',
    why: 'Spur between Big Laurel Creek and the Narrows Branch; the only North Face slope gentle enough for a logging railroad.',
    look: 'Visible switchback scars under second-growth forest.',
    near: 'Big Laurel Logging Grade, Big Laurel Millpond, the Narrows.',
    memorable: 'The old grade benches read like contour lines drawn on the mountain.' },
  { id: 'huckleberry-knob', kind: 'knob',
    where: 'South of Hemlock Knob, above the north arm of Calloway Lake',
    desc: 'A heath-covered knob of huckleberry and mountain laurel above oak forest, with ledges looking straight down onto the lake.',
    why: 'Short spur off the crest whose thin soils support heath rather than forest.',
    look: 'A rust-coloured knob in autumn above blue water.',
    near: 'Calloway Lake, Upper Cove, Tennalee Cove.',
    memorable: 'The best place to see the full branching outline of Calloway Lake.' },
  { id: 'bearpen-knob', kind: 'knob',
    where: 'Eastern end of the crest, above Hollow Reach',
    desc: 'The last high point before the crest drops into Hollow Reach: a rocky knob with a sheer eastern drop and the Bearpen Tunnel beneath its southern shoulder.',
    why: 'The crest ends abruptly where the drowned gorge of Hollow Reach cuts through the massif.',
    look: 'A dark headwall rising behind the western tower of the Gate Bridge.',
    near: 'Sawyer Gap, the Gate Shelf, Hollow Reach, Dogwood Mountain.',
    memorable: 'From the Gate Bridge it looks like the island\'s wall ends in a fist.' },
  { id: 'sheepback-bald', kind: 'grassy bald',
    where: 'North-west spur from Gooseberry Bald',
    desc: 'A long, smooth, grassy ridge grazed by cattle in summer, with a few wind-bent hawthorns.',
    why: 'Rounded ridge of deeply weathered schist that holds deep soil and has stayed open pasture.',
    look: 'A pale green whaleback above the Coldwater Valley.',
    near: 'Copperhead Knob, the Coldwater Valley, the Old Valley Road.',
    memorable: 'The only high summit where cattle graze, their bells audible from the valley.' },
  { id: 'cove-mountain', kind: 'mountain',
    where: 'Spur dividing the Ledford Prong valley from Tennalee Cove',
    desc: 'A heavily wooded mountain with a fire road to a small cleared summit and steep coves holding old-growth tulip poplar.',
    why: 'Spur between two drainages that funnel moist air into its coves.',
    look: 'Dark forested mass between the Ledford strip and the lake.',
    near: 'Calloway Lake, Ledford, Little River, Calloway Dam Road.',
    memorable: 'Its coves hold the largest trees on the island\'s south side.' },
  { id: 'brushy-mountain', kind: 'mountain',
    where: 'South spur between Hominy Creek and Ledford Prong',
    desc: 'A dry, oak-and-pine mountain on the sunny side of the crest, with an old burn scar of standing dead pine.',
    why: 'South-facing slopes dry out quickly and burn in drought years.',
    look: 'Lighter, patchier green than the coves around it.',
    near: 'Chestnut Knob, Lake Hominy, the Gap Road.',
    memorable: 'Grey snags of the old burn bristle along its crest.' },
  { id: 'rich-mountain', kind: 'mountain',
    where: 'North-west spur off Stormhead Mountain',
    desc: 'A rounded mountain of deep, dark soil with rich cove forests and an abandoned homestead clearing near the top.',
    why: 'Weathered mafic rock produces unusually fertile soils.',
    look: 'Exceptionally lush, dark canopy; a lone stone chimney in a meadow.',
    near: 'Rich Creek, Thunderstone, the Narrows Road.',
    memorable: 'The chimney standing alone in its clearing.' },
  { id: 'sugartree-knob', kind: 'knob',
    where: 'South spur from Painted Bald above Hominy',
    desc: 'A knob covered in sugar maple, with an old sugar-shack foundation and rusted kettles in a hollow below the summit.',
    why: 'North-facing hollows on the spur hold maples at a lower elevation than usual.',
    look: 'Blazes orange in October, a week before the surrounding oaks.',
    near: 'Sugartree Branch, Hominy, Painted Bald.',
    memorable: 'The earliest and brightest autumn colour visible from I-21.' },
  { id: 'dogwood-mountain', kind: 'mountain',
    where: 'East of Tennalee Cove above the Hollow Reach rim',
    desc: 'A broad, wooded mountain whose understorey of flowering dogwood turns the slopes white in April.',
    why: 'Spur that separates the cove from the steep Hollow Reach shore.',
    look: 'White spring bloom under bare canopy, visible from the Gate Road.',
    near: 'Dogwood Creek, Upper Cove, the Gate Road, Hollow Reach.',
    memorable: 'For two weeks each spring the mountain looks dusted with snow.' },
  { id: 'pinnacle-knob', kind: 'knob',
    where: 'West end of the crest above Shady Gap',
    desc: 'A small, steep knob with a rock outcrop at its point and the Parkway curling around its flank.',
    why: 'Last high ground before the crest drops into Shady Gap.',
    look: 'A pointed hill above the interstate corridor.',
    near: 'Shady Gap, I-21, the Parkway, Coldwater Valley.',
    memorable: 'Marks the start of the climb onto the crest.' },
  { id: 'chestnut-knob', kind: 'knob',
    where: 'Foothills between Hominy and Ledford',
    desc: 'A foothill knob with sprouting American chestnut stumps among oaks, and a cell tower on its summit.',
    why: 'Dry, acidic ridge soils once dominated by chestnut.',
    look: 'Low wooded hill with a single lattice tower.',
    near: 'Lake Hominy, I-21, Ledford.',
    memorable: 'Chestnut sprouts still push up from century-old root crowns.' },
  { id: 'copperhead-knob', kind: 'knob',
    where: 'East wall of the Coldwater Valley, north of Coldwater',
    desc: 'A rocky foothill knob with sunny limestone ledges and a small abandoned copper prospect pit.',
    why: 'Edge of the crystalline massif where it meets the limestone of the valley.',
    look: 'Grey ledges above green pasture.',
    near: 'Coldwater, Sheepback Bald, the Old Valley Road.',
    memorable: 'Overlooks the whole valley floor and the plateau escarpment opposite.' },
  { id: 'hogback', kind: 'ridge',
    where: 'Low ridge east of the Lower Tennalee Gorge, above Tennalee Falls',
    desc: 'A narrow, steep-sided ridge of hard quartzite that the Tennalee cuts through just below Calloway Dam.',
    why: 'Resistant quartzite forms a long hogback that holds up the gorge where the dam was built.',
    look: 'A sharp, wooded ridgeline above the falls town.',
    near: 'Calloway Dam, Tennalee Falls, the Lower Tennalee Gorge.',
    memorable: 'Its quartzite ledges frame both ends of the dam.' },
  { id: 'hickory-knob', kind: 'plateau knob',
    where: 'Northern Hickory Tableland',
    desc: 'The highest point on the sandstone plateau: a low, rocky rise of conglomerate in a forest of chestnut oak and pitch pine.',
    why: 'Remnant of a thicker caprock layer on the tilted plateau surface.',
    look: 'A slight swell in the otherwise level tableland horizon.',
    near: 'Hickory Lake, Cane Creek gorge, the Tableland Bluffs.',
    memorable: 'Pebble-studded conglomerate boulders that look like poured concrete.' },
  { id: 'lookout-bluff', kind: 'bluff',
    where: 'West edge of the Hickory Tableland above Serena Bay',
    desc: 'A sandstone promontory at the plateau rim, dropping 400 m to the bay in a single sweep of cliffs and wooded talus.',
    why: 'The plateau is being cut back by the sea, leaving headlands where the caprock is thickest.',
    look: 'A flat-topped prow of pale rock above the water.',
    near: 'Piney Cove, Hickory Tableland Airport, the Tableland Road.',
    memorable: 'Sunsets over Serena Bay with the whole Mirabel shoreline in view.' },

  // -------------------------------------------------------------- Graystone
  { id: 'whitlock-mountain', kind: 'mountain',
    where: 'Whitlock Range, north of Lake Whitlock',
    desc: 'The highest summit on Graystone: a granite-cored mountain with a bare south face of exfoliating rock sheets and a summit forest of red oak, rhododendron and scattered red spruce.',
    why: 'A large granite pluton that weathers into domes and sheets rather than ridges.',
    look: 'A pale, curved rock face above the village and lake.',
    near: 'Whitlock, Lake Whitlock, Hawkbill Knob, Lantern Mountain.',
    memorable: 'Its south face turns pink at sunrise above the still lake.' },
  { id: 'lantern-mountain', kind: 'mountain',
    where: 'Whitlock Range, east of Whitlock Mountain',
    desc: 'A broad summit topped by a white FAA radar dome and a lattice tower with red and white lights.',
    why: 'Second-highest point on the Graystone highlands with an unobstructed view out to sea.',
    look: 'A white golf ball on the skyline by day, a red pulse by night.',
    near: 'Bald Rock, Frostcap, Highlands Road, Ravenfork.',
    memorable: 'Visible from almost every island; the radar dome is a navigation mark for small planes.' },
  { id: 'frostcap', kind: 'mountain',
    where: 'Eastern Whitlock Range',
    desc: 'A cold, north-facing summit where rime ice coats the trees through much of the winter.',
    why: 'Exposed to winter northwest winds coming off the Narrows.',
    look: 'Silver-white crown of frosted trees on clear winter mornings.',
    near: 'Bright Water Lake, Ravenrock, the north-shore cliffs.',
    memorable: 'The only summit that looks snowy without snow.' },
  { id: 'sassafras-knob', kind: 'knob',
    where: 'Western Graystone highlands',
    desc: 'A wooded knob with a rock overlook facing south over the Blue Wall and the Piedmont strip.',
    why: 'Highland knob near the edge of the plateau escarpment.',
    look: 'Dark knob behind Pale Wall Mountain\'s cliff.',
    near: 'Pale Wall Mountain, Wolfpen Mountain, Hollow Creek.',
    memorable: 'A clear view of all three granite domes in a line below.' },
  { id: 'pale-wall', kind: 'cliff mountain',
    where: 'Southern edge of the highlands, west of Thunderhole Gorge',
    desc: 'A mountain whose south face is a sheer 230 m wall of white granite streaked with black lichen and seep stains.',
    why: 'Exfoliation joints parallel to the escarpment peel off huge sheets of granite.',
    look: 'A white wall visible from the sound and from Calder.',
    near: 'Glassface Dome, Thunderhole Gorge, the Whitlock Grade.',
    memorable: 'The largest single sheet of bare rock in the islands.' },
  { id: 'ravenrock', kind: 'mountain',
    where: 'Eastern highlands above Fallon',
    desc: 'A summit with a band of dark gneiss cliffs where ravens and peregrine falcons nest.',
    why: 'Dark gneiss roof pendant over the granite, more resistant than the rock around it.',
    look: 'Dark rock band under a wooded summit.',
    near: 'Hornet Spire, Fallon Knob, Highlands Road.',
    memorable: 'Raven calls echoing off the cliff band.' },
  { id: 'hawkbill-knob', kind: 'knob',
    where: 'Western end of the Whitlock Range above Hollow Reach',
    desc: 'A hooked summit ridge with a cliff facing Hollow Reach.',
    why: 'The range ends where Hollow Reach has cut it off.',
    look: 'A beak-shaped profile from the Gate Bridge.',
    near: 'Whitlock, Hollow Creek, Stillhouse Road.',
    memorable: 'Its silhouette looks like a hawk\'s bill.' },
  { id: 'bald-rock', kind: 'granite summit',
    where: 'Central highlands between Thunderhole Gorge and Lantern Mountain',
    desc: 'A bare granite summit with weathering pits that fill with rainwater and a fringe of stunted pine.',
    why: 'Granite dome too steep and smooth for soil to hold.',
    look: 'A pale bald patch on a forested plateau.',
    near: 'Anvil Rock, Highlands Road, Thunderhole Gorge.',
    memorable: 'Rain pools in the granite reflect the sky.' },
  { id: 'hornet-spire', kind: 'rock spire',
    where: 'Blue Wall edge west of the Bright Water Gorge',
    desc: 'A free-standing granite spire separated from the escarpment by a deep cleft.',
    why: 'Joint-controlled erosion has isolated a pillar of rock at the escarpment edge.',
    look: 'A pointed spire against the sky.',
    near: 'Bright Water Gorge, Anvil Rock, Highlands Road.',
    memorable: 'Visible from SR 64 as a needle above the forest.' },
  { id: 'fallon-knob', kind: 'knob',
    where: 'Eastern end of the highlands above the Fallon Cliffs',
    desc: 'The last summit before the highlands meet the sea, with a view down onto Fallon harbour.',
    why: 'The highland block ends here at the coast.',
    look: 'Wooded knob above cliffs and harbour.',
    near: 'Fallon, Cape Fallon Light, Highlands Road.',
    memorable: 'You can look straight down onto fishing boats from 1,180 m.' },
  { id: 'anvil-rock', kind: 'rock prow',
    where: 'Blue Wall edge south of Bald Rock',
    desc: 'A flat-topped prow of granite projecting from the escarpment edge, with a 300 m drop on three sides.',
    why: 'Resistant block at the escarpment edge undercut by the Blue Wall\'s retreat.',
    look: 'Anvil-shaped silhouette on the escarpment rim.',
    near: 'Bald Rock, Thunderhole Gorge, Grayback below.',
    memorable: 'The flat top is the most dramatic standing point on the Blue Wall.' },
  { id: 'glassface-dome', kind: 'granite dome',
    where: 'Below the Blue Wall, east of Thunderhole Gorge',
    desc: 'A huge granite dome projecting from the escarpment face; its south side is a 350 m sheet of bare rock that streams with seep water.',
    why: 'Exfoliating granite pluton exposed as the escarpment retreated.',
    look: 'In winter, ice on the wet rock turns the face into a mirror.',
    near: 'Pale Wall Mountain, the Whitlock Grade, Thunderhole Falls.',
    memorable: 'The shining face is visible from the ferry crossing the sound.' },
  { id: 'wolfpen-mountain', kind: 'mountain',
    where: 'Western Graystone above the Gate Shelf',
    desc: 'A long, forested mountain that descends in steps toward Lookoff Mountain.',
    why: 'Ridge that steps down from the highlands to the Piedmont.',
    look: 'Forested staircase above the Blue Wall Road.',
    near: 'Lookoff Mountain, Gate Shelf, the Blue Wall Road.',
    memorable: 'A forested staircase from the cliff edge down to the sound.' },
  { id: 'lookoff-mountain', kind: 'mountain',
    where: 'South-western Graystone above Hollow Reach mouth',
    desc: 'A steep-sided mountain with a cleared overlook facing Calder.',
    why: 'Southern end of the Wolfpen ridge.',
    look: 'Wooded peak above the sound.',
    near: 'Hollow Reach, Blue Wall Road, Cassena Sound.',
    memorable: 'The overlook frames the Calder skyline across the water.' },
  { id: 'grayback', kind: 'granite monadnock',
    where: 'Piedmont strip north-east of Graystone town',
    desc: 'A colossal bare granite dome rising 380 m from rolling farmland, with streaks of black lichen and pools of water on its summit.',
    why: 'A granite pluton more resistant than the surrounding schist, left standing as the land around it wore down.',
    look: 'A grey whale-back dome visible from everywhere on the south side of the island and from Calder.',
    near: 'Graystone, Quarry Creek, Bright Water Road, Cutstone.',
    memorable: 'The island is named for it.' },
  { id: 'cutstone-mountain', kind: 'granite hill',
    where: 'West of Graystone town',
    desc: 'A granite hill half cut away by the Cutstone Quarry, leaving terraced grey benches and a flooded pit.',
    why: 'Fine-grained granite close to the harbour and the railroad.',
    look: 'Stepped grey benches on one side, forest on the other.',
    near: 'Cutstone, Cutstone Quarry Hole, Blue Wall Incline.',
    memorable: 'Half natural mountain, half quarry.' },
  { id: 'graystone-head', kind: 'headland',
    where: 'South-east tip of Graystone at the mouth of Cassena Sound',
    desc: 'A rocky headland with low cliffs and a stubby white light tower.',
    why: 'Hard gneiss headland at the sound mouth.',
    look: 'Low cliffs with a light tower.',
    near: 'Bright Water mouth, Graystone Coast Road.',
    memorable: 'Ships turning into the sound pass close under it.' },

  // --------------------------------------------------------- Lowland hills
  { id: 'iron-mountain', kind: 'hill (local "mountain")',
    where: 'Red Hills, northern Bellamy',
    desc: 'A 118 m hill capped with iron-cemented sandstone, with red clay roadcuts and a stand of longleaf pine on top.',
    why: 'An ironstone cap protects the soft sands beneath from erosion.',
    look: 'Deep red clay banks on the roads around it.',
    near: 'Harlow, Chalk Pits, Sugarloaf Hill.',
    memorable: 'Locals call it a mountain; from the flat farm plain it looks like one.' },
  { id: 'sugarloaf-hill', kind: 'hill',
    where: 'Red Hills, north of Lake Ocosta',
    desc: 'A steep, conical hill of red sand capped with red cedars and a white survey post.',
    why: 'An erosional remnant of the old upland surface.',
    look: 'A dark cedar cone above flat fields.',
    near: 'Lake Ocosta, Red Hills Road.',
    memorable: 'Its dark cedar cap marks the hill for kilometres across the farmland.' },
  { id: 'calder-heights', kind: 'urban hill',
    where: 'Centre of Calder Island',
    desc: 'A granite-gneiss ridge in the middle of the city, topped by a stone-walled reservoir and a broadcast tower.',
    why: 'The bedrock knob that made Calder island dry and defensible.',
    look: 'Green hill rising from the grid of streets.',
    near: 'Heights Reservoir, the Heights district, Midtown.',
    memorable: 'The highest ground in the city, with views of the harbour.' },
  { id: 'scrub-hill', kind: 'sand ridge summit',
    where: 'Sandhill Ridge, central Wickham',
    desc: 'The highest point on Wickham: a dune summit of white sand with sand pine scrub and a fire lookout tower.',
    why: 'An ancient dune ridge left by higher seas.',
    look: 'White sand patches among dark scrub.',
    near: 'Punchbowl Sink, the Ridge Road, Blue Sink.',
    memorable: 'Barefoot-white sand 76 m above the sea.' },
  { id: 'firetower-hill', kind: 'sand ridge knob',
    where: 'Southern Sandhill Ridge',
    desc: 'A sandy knob with an old steel fire tower and longleaf savanna.',
    why: 'Southern continuation of the relict dune ridge.',
    look: 'Fire tower above open pine savanna.',
    near: 'Deep Lake, Little Sink, Ridge Road.',
    memorable: 'The tower overlooks both coasts of Wickham.' },
  { id: 'highpine-knoll', kind: 'ridge summit',
    where: 'Long Ridge, eastern Ossahatchee',
    desc: 'A low summit on the dune ridge with a fire tower and tall longleaf pines.',
    why: 'The highest point of the relict barrier ridge that dams the swamp.',
    look: 'Tall pines above the swamp canopy.',
    near: 'Long Ridge Pond, Tarrow Landing, Coastal Highway.',
    memorable: 'From the tower the swamp looks like a green sea.' },
  { id: 'kestrel-hill', kind: 'dune',
    where: 'Kestrel Island, Gannet Banks',
    desc: 'The tallest sand dune on the Atlantic coast of the archipelago: a migrating hill of bare sand 28 m high.',
    why: 'Wind-blown sand from a wide beach piles up where the barrier is widest.',
    look: 'Bare white dune rising above the village rooftops.',
    near: 'Kestrel, Kestrel Beach, Banks Highway.',
    memorable: 'People slide down it on cardboard and fly kites from the top.' },
];
