// Register: 50 viewpoints. `at` is the standing point, `eye` the height of
// the observer above ground (towers, decks), `facing` the main view bearing
// in degrees (0 = north, 90 = east; null = all-round). The builder computes
// which primary landmarks are actually visible from each point.

export const VIEWPOINTS = [
  // ---------------------------------------------------------------- Halcomb
  { id: 'vp-ledford-dome', name: 'Ledford Dome Observation Tower', island: 'halcomb', at: [29.0, 80.3], eye: 14, facing: null,
    desc: 'A concrete spiral ramp to a circular deck above the spruce–fir on the highest summit.',
    why: 'Highest point in the islands; the trees would otherwise block the view.',
    look: 'Pale ramp curling above a black conifer canopy.',
    near: 'Ledford Dome Road, Ledford Spruce–Fir Forest.',
    memorable: 'Every island is visible on a clear day.' },
  { id: 'ledford-gap-overlook', name: 'Ledford Gap Overlook', island: 'halcomb', at: [27.3, 79.75], eye: 2, facing: 0,
    desc: 'A stone-walled parking area at the crest of the Gap Road where it meets the Parkway.',
    why: 'The pass is the low point of the crest and looks straight down the North Face.',
    look: 'Stone wall, interpretive sign, and a sheer drop toward the Narrows.',
    near: 'Gap Road, Parkway, Coldspring Knob.',
    memorable: 'Clouds pouring through the gap from one side to the other.' },
  { id: 'painted-bald-view', name: 'Painted Bald', island: 'halcomb', at: [22.5, 78.0], eye: 2, facing: 210,
    desc: 'Open summit meadow with views in every direction.',
    why: 'Treeless bald summit.',
    look: 'Grass and azalea foreground, blue ridges beyond.',
    near: 'Parkway, Sugartree Knob.',
    memorable: 'Azaleas framing the whole western half of the archipelago.' },
  { id: 'vp-gooseberry', name: 'Gooseberry Fire Tower', island: 'halcomb', at: [17.0, 75.0], eye: 18, facing: 270,
    desc: 'A steel fire lookout cab on a grassy summit at the western end of the crest.',
    why: 'Built to watch the Coldwater Valley and the Tableland for smoke.',
    look: 'Steel stairs and a glass cab.',
    near: 'Gooseberry Bald, Gooseberry Pond, Parkway.',
    memorable: 'Sunset on the Tableland escarpment.' },
  { id: 'steeples-summit', name: 'The Steeples', island: 'halcomb', at: [38.8, 79.8], eye: 2, facing: 135,
    desc: 'A narrow rock perch between the twin slate spires.',
    why: 'Highest rock on the eastern crest.',
    look: 'Knife-edge rock with drops on both sides.',
    near: 'Sawyer Gap, Hemlock Knob.',
    memorable: 'Looking down on Calloway Lake and across to Graystone.' },
  { id: 'callahan-cliff-tops', name: 'Callahan Cliff Tops', island: 'halcomb', at: [32.9, 84.6], eye: 2, facing: 0,
    desc: 'Bare slate ledges at the top of Mount Callahan\'s north face.',
    why: 'Cliffs on the steepest mountain face in the islands.',
    look: 'Grey ledges and a 1,800 m drop to the strait.',
    near: 'Mount Callahan, Callahan Old-Growth Coves.',
    memorable: 'Ships in the Narrows look like toys.' },
  { id: 'lookout-bluff-view', name: 'Lookout Bluff', island: 'halcomb', at: [4.3, 76.0], eye: 2, facing: 260,
    desc: 'The tip of the sandstone promontory at the edge of the Tableland.',
    why: 'Western edge of the plateau above the bay.',
    look: 'Flat rock prow with Serena Bay below.',
    near: 'Tableland Road, Hickory Tableland Airport.',
    memorable: 'Sunsets over Serena Bay and the Mirabel coast.' },
  { id: 'hickory-falls-overlook', name: 'Hickory Falls Overlook', island: 'halcomb', at: [8.3, 81.1], eye: 2, facing: 90,
    desc: 'A railed platform at the plateau rim beside the brink of Hickory Falls.',
    why: 'Where the plateau stream leaps off the escarpment.',
    look: 'The falls dropping into a green gorge, with the Coldwater Valley beyond.',
    near: 'Hickory Falls, Hickory Lake.',
    memorable: 'The whole Coldwater Valley spread below.' },
  { id: 'tableland-switchback', name: 'Tableland Grade Pull-off', island: 'halcomb', at: [9.4, 79.3], eye: 2, facing: 90,
    desc: 'A gravel pull-off on the switchbacks of the Tableland Road.',
    why: 'Halfway up the escarpment.',
    look: 'Road switchbacks below and the valley beyond.',
    near: 'Tableland Road, Coldwater.',
    memorable: 'Watching valley fog from above at dawn.' },
  { id: 'calloway-dam-overlook', name: 'Calloway Dam Overlook', island: 'halcomb', at: [35.5, 70.2], eye: 2, facing: 0,
    desc: 'A viewing terrace on the dam crest between the lake and the gorge.',
    why: 'The dam spans the narrowest point of the gorge.',
    look: 'Lake on one side, a 135 m drop on the other.',
    near: 'Calloway Dam, Calloway Lake, Hogback.',
    memorable: 'Spillway gates opening in a flood.' },
  { id: 'thunderstone-overlook', name: 'Thunderstone Overlook', island: 'halcomb', at: [24.4, 78.6], eye: 2, facing: 340,
    desc: 'A Parkway pull-off facing the North Face spurs and the Narrows.',
    why: 'The Parkway crosses the crest just west of Ledford Gap.',
    look: 'Parallel spurs descending to the strait.',
    near: 'Parkway, Thunderstone Mountain.',
    memorable: 'Spurs lined up like folded cloth.' },
  { id: 'sawyer-gap-overlook', name: 'Sawyer Gap Overlook', island: 'halcomb', at: [41.5, 79.0], eye: 2, facing: 150,
    desc: 'Pull-off at the eastern end of the Parkway.',
    why: 'Low gap at the east end of the crest.',
    look: 'Upper Cove farms below, Graystone across Hollow Reach.',
    near: 'Parkway, Upper Cove, Bearpen Knob.',
    memorable: 'Farm fields deep in the mountains.' },
  { id: 'hominy-bay-overlook', name: 'Hominy Bay Overlook', island: 'halcomb', at: [21.0, 67.6], eye: 2, facing: 180,
    desc: 'A rest area on I-21 above Hominy Bay.',
    why: 'Where the interstate tops a foothill spur above the bay.',
    look: 'Wooded bay, sound and Bellamy beyond.',
    near: 'I-21, Hominy.',
    memorable: 'The first view of the sea for travellers from the mainland.' },
  { id: 'narrows-bridge-crest', name: 'Narrows Bridge Crest', island: 'halcomb', at: [12.1, 91.4], onStructure: true, eye: 45, facing: 180,
    desc: 'The top of the Narrows Bridge cantilever, seen from a car.',
    why: 'Bridge over the strait at its narrowest point.',
    look: 'Steel truss and the North Face rising ahead.',
    near: 'Narrows Bridge, Narrows Landing.',
    memorable: 'The first sight of the islands from the mainland.' },

  // -------------------------------------------------------------- Graystone
  { id: 'whitlock-summit', name: 'Whitlock Mountain Summit', island: 'graystone', at: [58.0, 85.4], eye: 2, facing: null,
    desc: 'Granite summit ledges above the lake.',
    why: 'Highest point on Graystone.',
    look: 'Granite slabs and stunted spruce.',
    near: 'Whitlock, Lake Whitlock.',
    memorable: 'Lake below, sea on three sides.' },
  { id: 'lantern-radar-view', name: 'Lantern Mountain', island: 'graystone', at: [63.4, 87.2], eye: 2, facing: 90,
    desc: 'Clearing beside the radar dome fence.',
    why: 'Summit cleared for the radar.',
    look: 'White dome above the clearing.',
    near: 'Highlands Road, Bald Rock.',
    memorable: 'Ocean horizon to the east.' },
  { id: 'pale-wall-rim', name: 'Pale Wall Rim', island: 'graystone', at: [56.0, 80.9], eye: 2, facing: 180,
    desc: 'The edge of the 230 m granite wall.',
    why: 'Top of the largest cliff in the islands.',
    look: 'Bare granite falling away to forest.',
    near: 'Glassface Dome, Whitlock Grade.',
    memorable: 'Standing above a sheer white wall.' },
  { id: 'glassface-pullout', name: 'Glassface Pull-off', island: 'graystone', at: [56.8, 76.6], eye: 2, facing: 90,
    desc: 'A switchback pull-off on the Whitlock Grade facing the dome.',
    why: 'The road passes close below the dome.',
    look: 'The shining rock face at eye level.',
    near: 'Whitlock Grade, Glassface Dome.',
    memorable: 'Ice-glazed rock in winter.' },
  { id: 'grayback-summit', name: 'Grayback Summit', island: 'graystone', at: [66.2, 73.6], eye: 2, facing: null,
    desc: 'The bare top of the granite monadnock.',
    why: 'Isolated dome rising above the plain.',
    look: 'Bare rock in all directions.',
    near: 'Grayback Granite Glades, Graystone.',
    memorable: 'The Blue Wall on one side, the sound on the other.' },
  { id: 'gate-bridge-deck', name: 'Gate Bridge', island: 'graystone', at: [46.1, 77.05], onStructure: true, eye: 4, facing: 0,
    desc: 'The suspension bridge deck 190 m above Hollow Reach.',
    why: 'The bridge crosses at the narrowest point of the gorge.',
    look: 'Gorge walls rising on both sides, water far below.',
    near: 'Gate Bridge, Veil Falls, Bearpen Tunnel.',
    memorable: 'Veil Falls visible up the gorge from the bridge.' },
  { id: 'veil-falls-rim', name: 'Veil Falls Rim', island: 'graystone', at: [49.3, 81.0], eye: 2, facing: 270,
    desc: 'The lip of the cliff where Hollow Creek falls into Hollow Reach.',
    why: 'The creek leaps the gorge wall.',
    look: 'Water vanishing over the edge.',
    near: 'Veil Falls, Hollow Creek.',
    memorable: 'Spray rising back up the cliff.' },
  { id: 'fallon-cliffs-pullout', name: 'Fallon Cliffs Pull-off', island: 'graystone', at: [77.4, 83.0], eye: 2, facing: 90,
    desc: 'A pull-off on the Coast Road at the cliff edge.',
    why: 'The road runs along the cliff top.',
    look: 'Ocean far below.',
    near: 'Coast Road, Fallon Cliff-Top Woods.',
    memorable: 'Gannets diving in the sea below.' },
  { id: 'cape-fallon-light-view', name: 'Cape Fallon Light', island: 'graystone', at: [77.5, 89.4], eye: 20, facing: 45,
    desc: 'The gallery of the lighthouse on the north arm of Fallon Cove.',
    why: 'The headland guarding the harbour.',
    look: 'Harbour, cliffs and open sea.',
    near: 'Fallon, Fallon Harbor.',
    memorable: 'Fishing boats returning at dusk.' },
  { id: 'anvil-rock-view', name: 'Anvil Rock', island: 'graystone', at: [64.2, 80.4], eye: 2, facing: 160,
    desc: 'The flat top of the granite prow.',
    why: 'Projecting rock on the escarpment edge.',
    look: 'Drop on three sides.',
    near: 'Bald Rock, Blue Wall Rainforest.',
    memorable: 'The whole Piedmont strip and the sound below.' },
  { id: 'ravenrock-ledges', name: 'Ravenrock Ledges', island: 'graystone', at: [71.5, 86.4], eye: 2, facing: 120,
    desc: 'Dark gneiss ledges near the summit.',
    why: 'Cliff band near the top.',
    look: 'Dark rock and wheeling ravens.',
    near: 'Highlands Road, Hornet Spire.',
    memorable: 'Falcons stooping past the ledges.' },
  { id: 'thunderhole-overlook', name: 'Thunderhole Gorge Overlook', island: 'graystone', at: [59.8, 79.6], eye: 2, facing: 160,
    desc: 'A rock ledge above the gorge with a view of Thunderhole Falls.',
    why: 'Rim of the gorge where the river crosses the Blue Wall.',
    look: 'White falls in a green gorge.',
    near: 'Thunderhole Falls, Thunderhole Gorge Forest.',
    memorable: 'The roar audible a kilometre away.' },

  // -------------------------------------------------------- Calder / Corliss
  { id: 'heights-park', name: 'Heights Reservoir Park', island: 'calder', at: [35.2, 58.6], eye: 2, facing: 45,
    desc: 'The promenade around the reservoir at the top of the Heights.',
    why: 'Highest ground in the city.',
    look: 'Skyline and harbour beyond the water.',
    near: 'Heights Reservoir, broadcast tower.',
    memorable: 'The skyline reflected in the reservoir.' },
  { id: 'calder-tower-deck', name: 'Calder Tower Observation Deck', island: 'calder', at: [37.8, 61.8], eye: 260, facing: null,
    desc: 'The observation floor at the top of the tallest building in the islands.',
    why: 'Downtown sits on the bluff at the river mouth.',
    look: 'Glass floor-to-ceiling windows.',
    near: 'Downtown, Old Market.',
    memorable: 'Night view of three bridges lit up.' },
  { id: 'tennalee-bridge-crest', name: 'Tennalee River Bridge Crest', island: 'calder', at: [33.75, 63.5], onStructure: true, eye: 30, facing: 90,
    desc: 'The high point of the interstate bridge into the city.',
    why: 'The bridge spans the North Channel.',
    look: 'Downtown towers ahead.',
    near: 'Tennalee River Bridge, Halcomb Heights.',
    memorable: 'The skyline appearing as you crest the bridge.' },
  { id: 'landfill-hill-view', name: 'Landfill Hill', island: 'corliss', at: [51.5, 57.3], eye: 2, facing: 0,
    desc: 'The grassy top of the capped landfill.',
    why: 'Highest point on flat Corliss.',
    look: 'Cranes, stacks and ships.',
    near: 'Corliss Generating Station, Cooling Pond.',
    memorable: 'Watching container ships berth.' },
  { id: 'harbor-bridge-view', name: 'Harbor Bridge', island: 'corliss', at: [42.6, 59.5], onStructure: true, eye: 18, facing: 0,
    desc: 'The bridge between Calder and Corliss.',
    why: 'Crosses the Inner Harbor.',
    look: 'Port cranes and the city.',
    near: 'Harbor Bridge, Inner Harbor.',
    memorable: 'City on one side, industry on the other.' },

  // ---------------------------------------------------------------- Bellamy
  { id: 'iron-mountain-view', name: 'Iron Mountain', island: 'bellamy', at: [14.5, 47.5], eye: 2, facing: 180,
    desc: 'A clearing on the ironstone cap.',
    why: 'Highest hill on Bellamy.',
    look: 'Farmland patchwork to the horizon.',
    near: 'Harlow, Chalk Pits.',
    memorable: 'Seeing the whole farm plain.' },
  { id: 'long-bridge-hump', name: 'Long Bridge Hump', island: 'bellamy', at: [34.0, 53.6], onStructure: true, eye: 40, facing: 0,
    desc: 'The high navigation span of the Long Bridge.',
    why: 'Ships pass under the hump.',
    look: 'City ahead, sound on both sides.',
    near: 'Long Bridge, Bellamy Bluffs.',
    memorable: 'The skyline rising out of the water.' },
  { id: 'sound-bluffs-view', name: 'Sound Bluffs', island: 'bellamy', at: [17.6, 51.8], eye: 2, facing: 0,
    desc: 'The top of the red clay bluffs on the north shore.',
    why: 'Bluffs of the Red Hills at the sound.',
    look: 'Red cliffs and the mountains across the sound.',
    near: 'Sound Bluffs Beach, Sugarloaf Hill.',
    memorable: 'The whole Halcomb range across the water.' },

  // ---------------------------------------------------------------- Mirabel
  { id: 'mirabel-pier-end', name: 'End of Mirabel Pier', island: 'mirabel', at: [3.2, 47.0], onStructure: true, eye: 6, facing: 270,
    desc: 'The T-head at the end of the fishing pier.',
    why: 'The pier extends past the surf.',
    look: 'Green water below, the strip behind.',
    near: 'Mirabel Pier, Pier Beach.',
    memorable: 'Sunset with the condo towers glowing behind.' },
  { id: 'cape-serena-light-view', name: 'Cape Serena Light', island: 'mirabel', at: [2.4, 24.4], eye: 30, facing: 220,
    desc: 'The gallery of the lighthouse on the foreland tip.',
    why: 'Lighthouse at the cape.',
    look: 'Beach ridges and dune lakes below.',
    near: 'Cape Serena Beach, Long Swale Lake.',
    memorable: 'The dune lakes in parallel rows.' },
  { id: 'mirabel-sands-roof', name: 'Mirabel Sands Rooftop', island: 'mirabel', at: [4.9, 44.2], eye: 95, facing: 90,
    desc: 'The rooftop of the tallest condominium tower.',
    why: 'The tallest building on the barrier.',
    look: 'Strip, sound and Bellamy farmland.',
    near: 'Condo Row, Mirabel Beach.',
    memorable: 'Both sides of the island at once.' },

  // -------------------------------------------------------- Saint Ambrose
  { id: 'bay-street-bluff', name: 'Bay Street Bluff', island: 'saint-ambrose', at: [54.9, 48.4], eye: 2, facing: 90,
    desc: 'The bluff-top promenade along Haversham\'s waterfront.',
    why: 'The town sits on the highest bluff on the river.',
    look: 'Marsh, river and shrimp boats.',
    near: 'Bay Street, Haversham Shrimp Docks.',
    memorable: 'Golden marsh at sunrise.' },
  { id: 'ambrose-inlet-crest', name: 'Ambrose Inlet Bridge', island: 'saint-ambrose', at: [70.6, 29.1], onStructure: true, eye: 22, facing: 90,
    desc: 'The high point of the inlet bridge.',
    why: 'High-rise span over the inlet.',
    look: 'Inlet shoals, the Banks running south.',
    near: 'Ambrose Inlet, Inlet Point.',
    memorable: 'The Banks stretching to the horizon.' },
  { id: 'bonnet-marsh-tower', name: 'Bonnet Marsh Tower', island: 'saint-ambrose', at: [65.0, 45.0], eye: 10, facing: 90,
    desc: 'A wooden observation tower in the marsh.',
    why: 'Built for birdwatchers.',
    look: 'Marsh to the horizon.',
    near: 'Bonnet River, Bonnet Marsh Hammocks.',
    memorable: 'Herons and egrets at eye level.' },

  // ---------------------------------------------------------------- Wickham
  { id: 'vp-scrub-hill', name: 'Scrub Hill Fire Tower', island: 'wickham', at: [13.5, 14.0], eye: 30, facing: null,
    desc: 'The steel fire tower on Wickham\'s highest point.',
    why: 'Fire lookout for the longleaf woods.',
    look: 'Forest in all directions.',
    near: 'Scrub Hill, Punchbowl Sink.',
    memorable: 'Both coasts visible.' },
  { id: 'firetower-hill-view', name: 'Fire Tower Hill', island: 'wickham', at: [13.2, 7.5], eye: 25, facing: 180,
    desc: 'An older fire tower at the south end of the ridge.',
    why: 'Second lookout on the ridge.',
    look: 'Longleaf savanna below.',
    near: 'Deep Lake, Sand Lake.',
    memorable: 'Sunrise over the swamp island.' },
  { id: 'cedar-point-view', name: 'Cedar Point', island: 'wickham', at: [10.6, 0.6], eye: 2, facing: 180,
    desc: 'The tip of Cedar Point at the fish houses.',
    why: 'Southernmost point of Wickham.',
    look: 'Oyster bars and open water.',
    near: 'Cedar Shoals, Cedar Light.',
    memorable: 'Sun setting over oyster bars.' },

  // ------------------------------------------------------------ Ossahatchee
  { id: 'highpine-tower', name: 'Highpine Fire Tower', island: 'ossahatchee', at: [60.0, 14.0], eye: 30, facing: 270,
    desc: 'Fire tower on Long Ridge.',
    why: 'Highest point on the island.',
    look: 'Swamp to the west, sound to the east.',
    near: 'Highpine Knoll, Long Ridge Longleaf.',
    memorable: 'The swamp as a green sea.' },
  { id: 'vp-big-water', name: 'Big Water Tower', island: 'ossahatchee', at: [41.4, 16.4], eye: 15, facing: 180,
    desc: 'A wooden observation tower at the end of a boardwalk.',
    why: 'Overlooks the open lake.',
    look: 'Lake and cypress.',
    near: 'Big Water, Ossahatchee Skyway.',
    memorable: 'Alligators below the tower.' },
  { id: 'skyway-view', name: 'Ossahatchee Skyway', island: 'ossahatchee', at: [42.6, 17.6], eye: 8, facing: 180,
    desc: 'The elevated viaduct of the Trail across the swamp.',
    why: 'The road crosses the deepest part of the swamp on a viaduct.',
    look: 'Treetops on both sides.',
    near: 'Big Water, the Trail.',
    memorable: 'Driving through the canopy.' },

  // ------------------------------------------------- Gannet Banks / Sabal
  { id: 'kestrel-hill-top', name: 'Kestrel Hill', island: 'gannet', at: [73.3, 23.9], eye: 2, facing: null,
    desc: 'The bare summit of the big dune.',
    why: 'Tallest dune on the Banks.',
    look: 'Ocean, sound and village.',
    near: 'Kestrel, Kestrel Beach.',
    memorable: 'Both ocean and sound at sunset.' },
  { id: 'cape-merrin-gallery', name: 'Cape Merrin Lighthouse', island: 'gannet', at: [84.2, 8.7], eye: 55, facing: 120,
    desc: 'The gallery of the tallest lighthouse in the islands.',
    why: 'Lighthouse at the cape.',
    look: 'Breakers over the shoals and the wind farm.',
    near: 'Cape Merrin Light, Merrin Woods.',
    memorable: 'Shoals breaking white kilometres offshore.' },
  { id: 'sheepshead-bridge-view', name: 'Sheepshead Inlet Bridge', island: 'gannet', at: [76.6, 17.4], onStructure: true, eye: 18, facing: 90,
    desc: 'The crest of the inlet bridge.',
    why: 'High-rise span over the inlet.',
    look: 'Inlet and ocean.',
    near: 'Shellbank, Sheepshead Inlet.',
    memorable: 'Fishing boats running the inlet.' },
  { id: 'sabal-bridges-view', name: 'Sabal Bridges', island: 'sabal', at: [44.0, 3.4], onStructure: true, eye: 6, facing: 180,
    desc: 'The low bridges to Sabal Key.',
    why: 'Bridges across the flats.',
    look: 'Clear water over seagrass.',
    near: 'Sabal Key, Sabal Landing.',
    memorable: 'The water colours of the flats.' },
];
